### Q1. 항암약 위약을 투여 받은 환자의 부작용은 감기약 위약을 투여 받은 환자의 부작용 분포와 차이가 있는가?

항암약(위약)을 투여 받은 환자 그룹의 관찰된 부작용

In [2]:
import pandas as pd
df = pd.DataFrame({ "항암약":[4,4,3,4,1,4,1,4,1,4,4,2,1,4,2,3,2,4,4,4] })
# 1: '아픔', 2: '조금 아픔', 3: '속쓰림', 4: '무증상'

c:\Users\dnwpg\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

감기약(위약)을 투여받은 환자들 중의 알려진 부작용 발생 비율

In [3]:
# 1. 아픔: 10%
# 2. 조금 아픔 5%
# 3. 속 쓰림 15%
# 4. 무증상: 70%

-	귀무가설(H0): 감기약(위약)의 부작용과 항암약(위약)의 부작용은 동일하다.
- 	대립가설(H1): 감기약(위약)의 부작용과 항암약(위약)의 부작용은 다르다.

 ### 1-1. 항암약을 투여 받은 환자 중 '무증상'의 비율을 0과 1사이로 구하시오.

In [4]:
l = len(df)
l
ans = (11/20)
ans

0.55

### 1-2. 감기약의 예상 부작용 비율과 항암약의 부작용 관찰값이 통계적으로 유의미하게 차이가 있는지 확인하려 한다. 카이 제곱 검정을 사용하여 검정 통계량을 구하시오.

In [8]:
ob = df["항암약"].value_counts().sort_index().to_list()
ex = [0.1*20,0.05*20,0.15*20,0.7*20]

In [9]:
from scipy import stats
stats.chisquare(ob,ex)

Power_divergenceResult(statistic=6.976190476190476, pvalue=0.07266054733847573)

### 1-3. 위의 p-값을 구하시오

### Q2. 다중 선형 회귀 문제

In [15]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/6_3/data6-3-2.csv")
df.head(2)

    solar  wind     o3  temperature
0   89.14  6.28  33.52         23.0
1  109.97  1.04  27.01         20.7

1. 다중 선형 회귀 모델을 구축하고, 독립변수 o3의 회귀계수를 구하시오.
- 독립변수: solar(태양 에너지), wind(바람의 세기), o3(오존 농도)
- 종속변수: temperature(온도)

In [16]:
from statsmodels.formula.api import ols
model = ols("temperature ~ solar + wind + o3",df).fit()
model.summary() #0.0749

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:            temperature   R-squared:                       0.044
Model:                            OLS   Adj. R-squared:                  0.014
Method:                 Least Squares   F-statistic:                     1.464
Date:                Tue, 16 Jun 2026   Prob (F-statistic):              0.229
Time:                        20:29:47   Log-Likelihood:                -195.45
No. Observations:                 100   AIC:                             398.9
Df Residuals:                      96   BIC:                             409.3
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     19.0507      1.994      9.555      0.000      15.093      23.008
solar          0.0039      0.015      0.251      0.802      -0.027       0.035
wind          -0.0252      0.090     -0.280      0.780      -0.204       0.153
o3             0.0749      0.036      2.079      0.040       0.003       0.146
==============================================================================
Omnibus:                        0.654   Durbin-Watson:                   2.328
Prob(Omnibus):                  0.721   Jarque-Bera (JB):                0.672
Skew:                           0.187   Prob(JB):                        0.715
Kurtosis:                       2.855   Cond. No.                     1.20e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.2e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

2. 데이터에서 'solar'와 'o3' 값을 고정한 상태에서, 'wind'의 세기가 증가함에 따라 'temperature'가 감소하는지를 검증하기 위해 다중 선형 회귀 분석을 수행하고, 이 때'wind'의 회귀 계수에 대한 p-value 값을 구하시오. (유의수준: 0.05)

In [17]:
model.pvalues["wind"]

0.779717720207165

3. solar:100, wind:5, o3:30일 때 예측값과 그에 대한 95% 신뢰구간을 구하시오.

In [ ]:
new_data = pd.DataFrame({
    "solar" : [100],
    "wind" : [5],
    "o3" : [30]
})
ans = model.get_prediction(new_data)
ans.summary_frame(0.05)
# 21.56163
# 21.213737	21.909524

,mean,mean_se,mean_ci_lower,mean_ci_upper,obs_ci_lower,obs_ci_upper
0,21.56163,0.175263,21.213737,21.909524,18.082985,25.040276