## 다중 분류 문제
- 난방 부하 단계를 예측해주세요!

- 예측할 값(y): Heat_Load (Very Low, Low, Medium, High, Very High)
- 평가: f1-macro
- data: train.csv, test.csv
- 제출 형식: result.csv파일을 아래와 같은 형식으로 제출
~~~
pred
Very Low
Low
High
...
Very High
~~~

### 답안 제출 참고
- pd.read_csv('result.csv') 로 제출 코드 확인

In [3]:
import pandas as pd
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/6_2/energy_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/6_2/energy_test.csv")
train.shape, test.shape

((537, 10), (231, 9))

In [6]:
train.head()
target = train.pop("Heat_Load")

In [13]:
train = train.drop("Roof",axis=1)
test = test.drop("Roof",axis=1)

In [14]:
test.head()

,Compac,Surf_Area,Wall_Area,Height,Orient,Glaze_Area,Glaze_Distr,Cool_Load
0,0.64,784.0,343.0,Short,South,0.40,4,22.25
1,0.82,612.5,318.5,Tall,North,0.40,3,32.43
2,0.76,661.5,416.5,Tall,South,0.10,5,33.64
3,0.74,686.0,245.0,Short,East,0.40,1,17.25
4,0.64,784.0,343.0,Short,North,0.25,5,20.13

In [19]:
tmp = ["Height","Orient"]
from sklearn.preprocessing import LabelEncoder
for i in tmp:
    le = LabelEncoder()
    train[i] = le.fit_transform(train[i])
    test[i] = le.transform(test[i])
train.head()

,Compac,Surf_Area,Wall_Area,Height,Orient,Glaze_Area,Glaze_Distr,Cool_Load
0,0.74,686.0,245.0,0,2,0.25,3,14.72
1,0.98,514.5,294.0,1,2,0.40,2,33.94
2,0.90,563.5,318.5,1,3,0.25,1,37.58
3,0.74,686.0,245.0,0,2,0.25,2,15.18
4,0.98,514.5,294.0,1,0,0.25,2,29.69

In [21]:
from sklearn.model_selection import train_test_split
x_tr,x_val,y_tr,y_val = train_test_split(
    train,
    target,
    test_size = 0.1,
    random_state = 0
)
x_tr.shape

(483, 8)

In [32]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=0)
model = rf.fit(x_tr,y_tr)
pred = model.predict(x_val)
pred

import lightgbm as lgb
lg = lgb.LGBMClassifier(random_state=0)
model = lg.fit(x_tr,y_tr)
pred1 = model.predict(x_val)
pred1

array(['Very High', 'Very Low', 'High', 'Very Low', 'High', 'Very Low',
       'Low', 'Low', 'Low', 'Low', 'High', 'Medium', 'High', 'Very Low',
       'Medium', 'Very High', 'Medium', 'Very Low', 'Low', 'Medium',
       'High', 'Very Low', 'High', 'Low', 'Low', 'Low', 'Low', 'Very Low',
       'Very Low', 'Very Low', 'High', 'Medium', 'Low', 'Very High',
       'Very Low', 'Very Low', 'High', 'Very High', 'Very Low', 'High',
       'High', 'Very High', 'High', 'Very Low', 'High', 'Very Low',
       'Very High', 'High', 'High', 'Very High', 'High', 'Very Low',
       'Low', 'Very High'], dtype=object)

In [33]:
from sklearn.metrics import f1_score
ans = f1_score(y_val,pred1,average = "macro")
ans

0.9657465384954582

In [31]:
pred = model.predict(test)
import pandas as pd
a = pd.DataFrame({
    "pred" : pred
})
a.to_csv("result.csv",index=False)