# 작업형2
- 빅데이터 분석기사 3회 실기
- 제공된 데이터
    - train.csv
    - test.csv
- 예측할 컬럼 : TravelInsurance

### 시험에서 제공된 코드
~~~
import pandas as pd
a = pd.read_csv("train.csv")
b = pd.read_csv('test.csv')

pd.DataFrame(변수).to_csv('000000000.csv')
~~~


### 보험가입 확률을 묻는 문제
~~~
# csv 형태
# index,y_pred
# 0,0.152467
# 1,0.961511
# 2,0.151313
# 3,0.236632
...
# 494,0.121372
# 495,0.965155
# 496,0.986405

~~~

## 데이터 불러오기

In [1]:
import pandas as pd
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/3_2/train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/3_2/test.csv")

c:\Users\dnwpg\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

## EDA

In [2]:
# 크기 확인
train.shape, test.shape

((1490, 10), (497, 9))

In [3]:
# 샘플 확인
train.head()

,Unnamed: 0,Age,Employment Type,GraduateOrNot,AnnualIncome,FamilyMembers,ChronicDiseases,FrequentFlyer,EverTravelledAbroad,TravelInsurance
0,888,28,Private Sector/Self Employed,Yes,1250000,6,1,No,No,0
1,1308,31,Private Sector/Self Employed,Yes,1250000,7,1,No,No,0
2,151,29,Private Sector/Self Employed,Yes,1200000,7,0,No,No,1
3,396,33,Government Sector,Yes,650000,6,1,No,No,1
4,135,28,Private Sector/Self Employed,Yes,800000,6,0,No,Yes,1

In [4]:
test.head()

,Unnamed: 0,Age,Employment Type,GraduateOrNot,AnnualIncome,FamilyMembers,ChronicDiseases,FrequentFlyer,EverTravelledAbroad
0,920,32,Government Sector,Yes,650000,5,0,No,No
1,777,27,Government Sector,Yes,500000,5,0,No,No
2,696,32,Government Sector,Yes,350000,2,0,No,No
3,907,26,Private Sector/Self Employed,Yes,1400000,6,0,No,Yes
4,675,27,Private Sector/Self Employed,No,350000,3,0,No,No

In [7]:
# 타입 확인
print(train.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1490 entries, 0 to 1489
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           1490 non-null   int64
 1   Age                  1490 non-null   int64
 2   Employment Type      1490 non-null   object
 3   GraduateOrNot        1490 non-null   object
 4   AnnualIncome         1490 non-null   int64
 5   FamilyMembers        1490 non-null   int64
 6   ChronicDiseases      1490 non-null   int64
 7   FrequentFlyer        1490 non-null   object
 8   EverTravelledAbroad  1490 non-null   object
 9   TravelInsurance      1490 non-null   int64
dtypes: int64(6), object(4)
memory usage: 116.5+ KB
None

In [8]:
print(test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 497 entries, 0 to 496
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           497 non-null    int64
 1   Age                  497 non-null    int64
 2   Employment Type      497 non-null    object
 3   GraduateOrNot        497 non-null    object
 4   AnnualIncome         497 non-null    int64
 5   FamilyMembers        497 non-null    int64
 6   ChronicDiseases      497 non-null    int64
 7   FrequentFlyer        497 non-null    object
 8   EverTravelledAbroad  497 non-null    object
dtypes: int64(5), object(4)
memory usage: 35.1+ KB
None

In [9]:
# 결측치 확인 train
train.isnull().sum()

Unnamed: 0             0
Age                    0
Employment Type        0
GraduateOrNot          0
AnnualIncome           0
FamilyMembers          0
ChronicDiseases        0
FrequentFlyer          0
EverTravelledAbroad    0
TravelInsurance        0
dtype: int64

In [10]:
# 결측치 확인 test
test.isnull().sum()

Unnamed: 0             0
Age                    0
Employment Type        0
GraduateOrNot          0
AnnualIncome           0
FamilyMembers          0
ChronicDiseases        0
FrequentFlyer          0
EverTravelledAbroad    0
dtype: int64

In [ ]:
# 기초 통계 획인

In [ ]:
# 기초 통계 획인 object

In [11]:
# 타겟(레이블)
print(train.shape)
target = train.pop("TravelInsurance")
print(train.shape)

(1490, 10)
(1490, 9)

## 데이터 전처리 및 피처엔지니어링

In [19]:
train.head()

,Unnamed: 0,Age,Employment Type,GraduateOrNot,AnnualIncome,FamilyMembers,ChronicDiseases,FrequentFlyer,EverTravelledAbroad
0,888,28,Private Sector/Self Employed,Yes,1250000,6,1,No,No
1,1308,31,Private Sector/Self Employed,Yes,1250000,7,1,No,No
2,151,29,Private Sector/Self Employed,Yes,1200000,7,0,No,No
3,396,33,Government Sector,Yes,650000,6,1,No,No
4,135,28,Private Sector/Self Employed,Yes,800000,6,0,No,Yes

In [22]:
train = train.drop("Unnamed: 0",axis=1)
test = test.drop("Unnamed: 0",axis=1)

In [23]:
train = pd.get_dummies(train)
test = pd.get_dummies(test)

## 검증데이터 분리

In [31]:
# 검증데이터 분리
from sklearn.model_selection import train_test_split
x_tr,x_val,y_tr,y_val = train_test_split(train,target,test_size=0.2,random_state=0)
x_tr.shape, y_tr.shape

((1192, 12), (1192,))

## 모델 학습 및 예측

In [43]:
# 랜덤포레스트
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(x_tr,y_tr)
pred = rf.predict_proba(x_val)[:,1]
pred

array([0.74      , 0.89595238, 0.33      , 0.45      , 0.99      ,
       0.28983333, 0.97      , 0.13285714, 1.        , 0.97      ,
       0.6825    , 0.015     , 1.        , 0.35416667, 0.17083333,
       0.17416667, 0.62988095, 0.1185    , 0.45916667, 0.81      ,
       0.1675    , 0.22      , 0.15      , 0.005     , 0.51      ,
       0.03666667, 0.045     , 1.        , 0.075     , 0.96416667,
       0.20242857, 1.        , 0.26961111, 0.42116667, 1.        ,
       0.669     , 0.31188095, 0.00166667, 0.0075    , 0.10158333,
       0.04666667, 0.05333333, 0.22147619, 0.53433333, 0.17      ,
       0.84      , 0.05      , 0.20166667, 0.02      , 0.33      ,
       0.1215    , 0.02610714, 0.21333333, 0.85916667, 0.18919264,
       0.27      , 0.07264286, 0.37333333, 0.02      , 0.01      ,
       0.00666667, 0.1592803 , 0.024     , 1.        , 0.82783333,
       0.32288209, 0.15516667, 0.145     , 0.03      , 0.82321429,
       0.025     , 0.01      , 0.34054004, 0.1475    , 0.03      ,
       0.28      , 0.71      , 0.21333333, 0.95      , 0.04      ,
       0.97166667, 0.18      , 0.13      , 0.39131999, 0.        ,
       0.09      , 0.32772222, 0.059     , 0.82783333, 0.395     ,
       0.1       , 0.3137619 , 0.98      , 1.        , 0.16915079,
       0.11932552, 0.18      , 0.25      , 0.13      , 0.05783333,
       0.        , 0.21      , 0.41402381, 0.42083333, 0.332     ,
       0.02982684, 0.00333333, 0.97      , 0.04430952, 0.2855    ,
       0.66666667, 0.        , 0.19      , 1.        , 0.36      ,
       0.14733333, 0.41404762, 0.99      , 0.56      , 1.        ,
       0.98166667, 0.9       , 0.11833333, 0.39131999, 1.        ,
       0.24      , 0.        , 0.13333333, 0.9       , 0.14261111,
       0.25722222, 0.59      , 0.9       , 0.05849206, 0.15042729,
       0.20852381, 0.2562619 , 0.97      , 0.74      , 0.51      ,
       0.02      , 0.48457937, 0.81      , 0.61535714, 0.97      ,
       0.20166667, 0.42983333, 1.        , 0.85      , 0.98      ,
       0.85166667, 0.09      , 0.46466667, 0.26666667, 0.9       ,
       0.91875   , 0.98      , 0.00285714, 0.05666667, 0.184     ,
       0.04523232, 0.32288209, 0.03      , 0.        , 0.2       ,
       0.03933333, 0.17416667, 0.        , 0.        , 0.10047222,
       0.07964286, 0.        , 0.08      , 0.89      , 0.94      ,
       0.015     , 0.82      , 0.99      , 0.267     , 0.14261111,
       0.41404762, 0.17785714, 0.805     , 0.059     , 0.222     ,
       0.024     , 0.0045    , 0.62988095, 0.635     , 0.48466667,
       0.        , 0.63366667, 0.93333333, 0.04683333, 0.14633333,
       0.97      , 0.        , 0.0104329 , 1.        , 0.01      ,
       0.71666667, 0.11416667, 0.57      , 0.0275    , 1.        ,
       0.00775   , 0.42083333, 0.21333333, 0.0199329 , 0.94      ,
       0.04      , 0.02610714, 0.05      , 0.132     , 0.07666667,
       0.12666667, 0.37765873, 0.62      , 0.21785714, 0.33332756,
       0.1285    , 0.424     , 0.98      , 1.        , 0.45516667,
       0.621     , 0.8       , 0.15042729, 0.        , 1.        ,
       0.84      , 0.53      , 0.0225    , 0.059     , 0.183     ,
       0.1       , 0.99      , 0.015     , 1.        , 0.68797222,
       0.0075    , 0.12      , 0.9       , 0.53      , 0.48      ,
       0.45966667, 0.13      , 0.14      , 0.07932576, 0.91516667,
       0.49221429, 0.85      , 0.        , 0.50333333, 0.1       ,
       0.803     , 0.03      , 0.48457937, 0.45516667, 0.81      ,
       0.        , 0.99      , 0.066     , 0.07264286, 0.11      ,
       0.16605556, 0.81313095, 0.70178571, 0.25      , 0.095     ,
       0.        , 0.15266667, 0.97      , 0.45883333, 0.04      ,
       0.005     , 0.25041667, 0.11833333, 0.24      , 0.18416667,
       0.00583333, 0.49      , 0.66666667, 0.4235    , 0.38666667,
       0.        , 0.84      , 0.13833333, 0.724     , 0.03      ,
       0.26961111, 0.26      , 0.87833333, 0.69      , 0.20852381,
       0.38      , 1.        , 0.98      ])

In [44]:
# 평가
from sklearn.metrics import roc_auc_score
ans = roc_auc_score(y_val,pred)
ans

0.8137914230019492

## 예측

In [ ]:
# test 예측

In [ ]:
# csv 파일1 생성 (예시와 다른 형태)

In [ ]:
# csv 파일2 생성

In [ ]:
# csv 파일1 확인

In [ ]:
# csv 파일2 확인

## 체점
- 수험자는 알 수 없는 부분임

In [ ]:
# y_test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/3_2/y_test.csv")
# roc_auc_score(y_test, pred)

In [ ]:
# 당신의 score는?: 0.7875693000693