# Section4

In [55]:
import pandas as pd
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p2/hr_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p2/hr_test.csv")

In [56]:
train.shape, test.shape

((15326, 14), (3832, 13))

In [57]:
train.head()

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,30266,city_84,0.698,Male,No relevent experience,Full time course,High School,NaN,1,100-500,Pvt Ltd,never,15,0.0
1,13254,city_16,0.910,Male,Has relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,1,4,0.0
2,31675,city_21,0.624,Male,No relevent experience,Full time course,High School,NaN,3,NaN,NaN,never,12,0.0
3,30804,city_104,0.924,Male,No relevent experience,no_enrollment,Graduate,Arts,>20,NaN,NaN,2,258,1.0
4,18269,city_143,0.740,Male,Has relevent experience,no_enrollment,Graduate,STEM,12,50-99,Pvt Ltd,1,3,0.0

In [58]:
test.head()

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours
0,23044,city_136,0.897,Female,No relevent experience,Full time course,Masters,STEM,8,100-500,Public Sector,1,35
1,29611,city_21,0.624,NaN,Has relevent experience,no_enrollment,Graduate,STEM,16,<10,Pvt Ltd,>4,134
2,22483,city_21,0.624,NaN,Has relevent experience,no_enrollment,Graduate,STEM,5,10000+,Pvt Ltd,1,92
3,2660,city_103,0.920,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,100-500,Funded Startup,>4,6
4,29216,city_65,0.802,Male,Has relevent experience,no_enrollment,Graduate,STEM,15,<10,Pvt Ltd,>4,61

In [59]:
## id제거
train = train.drop("enrollee_id",axis=1)
test = test.drop("enrollee_id",axis=1)

In [60]:
cols = train.select_dtypes(include = ["O"]).columns
print(cols)

Index(['city', 'gender', 'relevent_experience', 'enrolled_university',
       'education_level', 'major_discipline', 'experience', 'company_size',
       'company_type', 'last_new_job'],
      dtype='object')

In [61]:
from sklearn.preprocessing import LabelEncoder
for i in cols:
    le = LabelEncoder()
    train[i] = le.fit_transform(train[i])
    test[i] = le.transform(test[i])
train.head()

,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,113,0.698,1,1,0,1,6,0,1,5,5,15,0.0
1,48,0.910,1,0,2,0,5,6,4,5,0,4,0.0
2,64,0.624,1,1,0,1,6,13,8,6,5,12,0.0
3,6,0.924,1,1,2,0,0,21,8,6,1,258,1.0
4,37,0.740,1,0,2,0,5,3,4,5,0,3,0.0

In [62]:
train.head()

,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,113,0.698,1,1,0,1,6,0,1,5,5,15,0.0
1,48,0.910,1,0,2,0,5,6,4,5,0,4,0.0
2,64,0.624,1,1,0,1,6,13,8,6,5,12,0.0
3,6,0.924,1,1,2,0,0,21,8,6,1,258,1.0
4,37,0.740,1,0,2,0,5,3,4,5,0,3,0.0

In [63]:
target = train.pop("target")
from sklearn.model_selection import train_test_split
x_tr, x_val, y_tr, y_val = train_test_split(
    train,
    target,
    test_size = 0.2,
    random_state = 0
)

In [88]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(x_tr,y_tr)
pred_proba = rf.predict_proba(x_val)
print(pred_proba)

[[0.72 0.28]
 [0.39 0.61]
 [0.89 0.11]
 ...
 [0.59 0.41]
 [0.99 0.01]
 [0.45 0.55]]

In [89]:
from sklearn.metrics import roc_auc_score
tmp = roc_auc_score(y_val, pred_proba[:,1])
print(tmp)

0.7649398181315877

In [90]:
pred = rf.predict_proba(test)
pred[:,1]

array([0.24, 0.35, 0.58, ..., 0.06, 0.21, 0.14])

In [91]:
a = pd.DataFrame({
    "pred" : pred[:,1]
})

In [92]:
a

      pred
0     0.24
1     0.35
2     0.58
3     0.07
4     0.03
...    ...
3827  0.18
3828  0.27
3829  0.06
3830  0.21
3831  0.14

[3832 rows x 1 columns]

In [53]:
# 1. 문제정의
# 평가: roc-auc
# target: target
# 최종파일: result.csv(컬럼 1개 pred, 1확률값)

# 2. 라이브러리 및 데이터 불러오기
import pandas as pd
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p2/hr_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p2/hr_test.csv")

# 3. 탐색적 데이터 분석(EDA)
print("===== 데이터 정보(자료형) =====")
print(train.info())

print("\n ===== train 결측치 수 =====")
print(train.isnull().sum())

print("\n ===== test 결측치 수 =====")
print(test.isnull().sum())

print("\n ===== train/test 카테고리별 수 =====")
print(train.nunique())
print(test.nunique())

print("\n ===== target 빈도 =====")
print(train['target'].value_counts())

===== 데이터 정보(자료형) =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15326 entries, 0 to 15325
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             15326 non-null  int64
 1   city                    15326 non-null  object
 2   city_development_index  15326 non-null  float64
 3   gender                  11750 non-null  object
 4   relevent_experience     15326 non-null  object
 5   enrolled_university     15012 non-null  object
 6   education_level         14961 non-null  object
 7   major_discipline        13045 non-null  object
 8   experience              15272 non-null  object
 9   company_size            10539 non-null  object
 10  company_type            10383 non-null  object
 11  last_new_job            14984 non-null  object
 12  training_hours          15326 non-null  int64
 13  target                  15326 non-null  float64
dtypes: float64(2), int64(2), object(10)
memory usage: 1.6+ MB
None

 ===== train 결측치 수 =====
enrollee_id                  0
city                         0
city_development_index       0
gender                    3576
relevent_experience          0
enrolled_university        314
education_level            365
major_discipline          2281
experience                  54
company_size              4787
company_type              4943
last_new_job               342
training_hours               0
target                       0
dtype: int64

 ===== test 결측치 수 =====
enrollee_id                  0
city                         0
city_development_index       0
gender                     932
relevent_experience          0
enrolled_university         72
education_level             95
major_discipline           532
experience                  11
company_size              1151
company_type              1197
last_new_job                81
training_hours               0
dtype: int64

 ===== train/test 카테고리별 수 =====
enrollee_id               15326
city                        123
city_development_index       93
gender                        3
relevent_experience           2
enrolled_university           3
education_level               5
major_discipline              6
experience                   22
company_size                  8
company_type                  6
last_new_job                  6
training_hours              241
target                        2
dtype: int64
enrollee_id               3832
city                       113
city_development_index      87
gender                       3
relevent_experience          2
enrolled_university          3
education_level              5
major_discipline             6
experience                  22
company_size                 8
company_type                 6
last_new_job                 6
training_hours             235
dtype: int64

 ===== target 빈도 =====
target
0.0    11517
1.0     3809
Name: count, dtype: int64

In [54]:
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p2/hr_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p2/hr_test.csv")

# 4. 데이터 전처리
target = train.pop('target')

# 결측치 처리
train = train.fillna("X")
test = test.fillna("X")

# train과 test 합쳐서 원핫인코딩
combined = pd.concat([train, test])
combined_dummies = pd.get_dummies(combined)
n_train = len(train)
train = combined_dummies[:n_train]
test = combined_dummies[n_train:]

# 5. 검증 데이터 분할
from sklearn.model_selection import train_test_split
X_tr, X_val, y_tr, y_val = train_test_split(train, target, test_size=0.2, random_state=0)

# 6. 머신러닝 학습 및 평가
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=0)
rf.fit(X_tr, y_tr)
pred = rf.predict_proba(X_val)

from sklearn.metrics import roc_auc_score
roc_auc = roc_auc_score(y_val, pred[:,1])
print('roc_auc:', roc_auc)

# 7. 예측 및 결과 파일 생성
pred = rf.predict_proba(test)
submit = pd.DataFrame({'pred':pred[:,1]})
submit.to_csv("result.csv", index=False)

roc_auc: 0.7730742036233207