##문제
제공된 학습용 데이터(train.csv)는 서울시 각 시군구별 건물 및 시설 현황 데이터이다.
학습용 데이터를 활용하여 총가스사용량을 예측하는 모형을 개발하고, 모형을 평가용 데이터(test.csv)에 적용하여 총가스사용량을 예측하시오.

예측 결과는 아래의 [유의 사항]과 [제출 형식]을 준수하여, CSV 파일(result.csv)을 생성하는 코드를 제출하시오.

---

[유의 사항]

① 예측 결과는 RMSE(Root Mean Squared Error) 평가 지표에 따라 평가함

② 타겟 변수(총가스사용량)는 일부 값이 0으로 기재되어 있으며, 이는 결측치를 대체한 값임.

[제출 형식]

① CSV 파일명: result.csv

② 예측 총가스사용량 컬럼명: pred

③ 제출 컬럼 개수: pred 컬럼 1개

④ 평가용 데이터 개수와 예측 결과 데이터 개수 일치: 1,476개

---

[제공 데이터]
- train.csv: 학습용 데이터, 약 3,196개
- test.csv: 평가용 데이터, 약 1,476개
평가용 데이터에는 총가스사용량 컬럼 미제공

[CSV 파일 형식 및 확인 방법]
- CSV 파일명: result.csv
- 예측 총가스사용량 컬럼명: pred
- 제출 CSV 파일 예시
~~~
pred
8790
14748
21560
761
~~~

In [36]:
# 데이터 불러오기
import pandas as pd
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/10_2/gas_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/10_2/gas_test.csv")

In [37]:
print(train.shape)
cond = train["총가스사용량"] == 0
train = train[~cond]
print(train.shape)
target = train.pop("총가스사용량")

(3196, 6)
(3139, 6)

In [38]:
help(pd.get_dummies)
train = pd.get_dummies(train)
test = pd.get_dummies(test)

Help on function get_dummies in module pandas.core.reshape.encoding:

get_dummies(data, prefix=None, prefix_sep: 'str | Iterable[str] | dict[str, str]' = '_', dummy_na: 'bool' = False, columns=None, sparse: 'bool' = False, drop_first: 'bool' = False, dtype: 'NpDtype | None' = None) -> 'DataFrame'
    Convert categorical variable into dummy/indicator variables.

    Each variable is converted in as many 0/1 variables as there are different
    values. Columns in the output are each named after a value; if the input is
    a DataFrame, the name of the original variable is prepended to the value.

    Parameters
    ----------
    data : array-like, Series, or DataFrame
        Data of which to get dummy indicators.
    prefix : str, list of str, or dict of str, default None
        String to append DataFrame column names.
        Pass a list with length equal to the number of columns
        when calling get_dummies on a DataFrame. Alternatively, `prefix`
        can be a dictionary mapping column names to prefixes.
    prefix_sep : str, default '_'
        If appending prefix, separator/delimiter to use. Or pass a
        list or dictionary as with `prefix`.
    dummy_na : bool, default False
        Add a column to indicate NaNs, if False NaNs are ignored.
    columns : list-like, default None
        Column names in the DataFrame to be encoded.
        If `columns` is None then all the columns with
        `object`, `string`, or `category` dtype will be converted.
    sparse : bool, default False
        Whether the dummy-encoded columns should be backed by
        a :class:`SparseArray` (True) or a regular NumPy array (False).
    drop_first : bool, default False
        Whether to get k-1 dummies out of k categorical levels by removing the
        first level.
    dtype : dtype, default bool
        Data type for new columns. Only a single dtype is allowed.

    Returns
    -------
    DataFrame
        Dummy-coded data. If `data` contains other columns than the
        dummy-coded one(s), these will be prepended, unaltered, to the result.

    See Also
    --------
    Series.str.get_dummies : Convert Series of strings to dummy codes.
    :func:`~pandas.from_dummies` : Convert dummy codes to categorical ``DataFrame``.

    Notes
    -----
    Reference :ref:`the user guide <reshaping.dummies>` for more examples.

    Examples
    --------
    >>> s = pd.Series(list('abca'))

    >>> pd.get_dummies(s)
           a      b      c
    0   True  False  False
    1  False   True  False
    2  False  False   True
    3   True  False  False

    >>> s1 = ['a', 'b', np.nan]

    >>> pd.get_dummies(s1)
           a      b
    0   True  False
    1  False   True
    2  False  False

    >>> pd.get_dummies(s1, dummy_na=True)
           a      b    NaN
    0   True  False  False
    1  False   True  False
    2  False  False   True

    >>> df = pd.DataFrame({'A': ['a', 'b', 'a'], 'B': ['b', 'a', 'c'],
    ...                    'C': [1, 2, 3]})

    >>> pd.get_dummies(df, prefix=['col1', 'col2'])
       C  col1_a  col1_b  col2_a  col2_b  col2_c
    0  1    True   False   False    True   False
    1  2   False    True    True   False   False
    2  3    True   False   False   False    True

    >>> pd.get_dummies(pd.Series(list('abcaa')))
           a      b      c
    0   True  False  False
    1  False   True  False
    2  False  False   True
    3   True  False  False
    4   True  False  False

    >>> pd.get_dummies(pd.Series(list('abcaa')), drop_first=True)
           b      c
    0  False  False
    1   True  False
    2  False   True
    3  False  False
    4  False  False

    >>> pd.get_dummies(pd.Series(list('abc')), dtype=float)
         a    b    c
    0  1.0  0.0  0.0
    1  0.0  1.0  0.0
    2  0.0  0.0  1.0

In [39]:
train.head()

,생활및판매,공공문화,복지의료,업무오락체육,시군구명_강남구,시군구명_강동구,시군구명_강북구,시군구명_관악구,시군구명_광진구,시군구명_구로구,...,시군구명_서초구,시군구명_성동구,시군구명_성북구,시군구명_송파구,시군구명_양천구,시군구명_영등포구,시군구명_용산구,시군구명_은평구,시군구명_종로구,시군구명_중구
0,2,0,0,0,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
1,6,0,1,2,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
2,27,0,0,0,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
3,2,0,0,0,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
4,83,0,1,19,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
from sklearn.model_selection import train_test_split
x_tr,x_val,y_tr,y_val = train_test_split(
    train,
    target,
    test_size = 0.2,
    random_state = 0
)
x_tr.shape

(2511, 25)

In [45]:
import sklearn
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor()
model = rf.fit(x_tr,y_tr)
pred = model.predict(x_val)

In [50]:
from sklearn.metrics import root_mean_squared_error
ans = root_mean_squared_error(pred,y_val)
ans

667.6457076223362

In [51]:
ans = model.predict(test)
result = pd.DataFrame({
    "pred" : ans
})
result

              pred
0     10361.634116
1     10757.662002
2      8791.861478
3     10361.634116
4     11222.044796
...            ...
1471  12180.769558
1472  10687.069536
1473   9792.085474
1474   9782.288913
1475  10649.909137

[1476 rows x 1 columns]

## EDA

In [ ]:

# 문제정의
# 평가: RMSE
# target: 총가스사용량
# 최종파일: result.csv(컬럼 1개 pred)

# 라이브러리 및 데이터 불러오기
import pandas as pd
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/10_2/gas_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/10_2/gas_test.csv")

# 탐색적 데이터 분석(EDA)
print("===== 데이터 크기 =====")
print("Train Shape:", train.shape)
print("Test Shape:", test.shape)

print("\n ===== 데이터 샘플 =====")
print(train.head())

print("\n ===== 데이터 정보(자료형) =====")
print(train.info())

print("\n ===== train object컬럼 unique 수 =====")
print(train.describe(include='object'))

print("\n ===== test object컬럼 unique 수 =====")
print(test.describe(include='object'))

print("\n ===== train 결측치 수 =====")
print(train.isnull().sum().sum())

print("\n ===== test 결측치 수 =====")
print(test.isnull().sum().sum())

print("\n ===== target 기술 통계 =====")
print(train['총가스사용량'].describe())

===== 데이터 크기 =====
Train Shape: (3196, 6)
Test Shape: (1476, 5)

 ===== 데이터 샘플 =====
  시군구명  생활및판매  공공문화  복지의료  업무오락체육   총가스사용량
0  구로구      2     0     0       0   9077.8
1  구로구      6     0     1       2  10105.5
2  구로구     27     0     0       0   8603.6
3  구로구      2     0     0       0  11076.8
4  구로구     83     0     1      19  10781.4

 ===== 데이터 정보(자료형) =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3196 entries, 0 to 3195
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   시군구명    3196 non-null   object
 1   생활및판매   3196 non-null   int64
 2   공공문화    3196 non-null   int64
 3   복지의료    3196 non-null   int64
 4   업무오락체육  3196 non-null   int64
 5   총가스사용량  3196 non-null   float64
dtypes: float64(1), int64(4), object(1)
memory usage: 149.9+ KB
None

 ===== train object컬럼 unique 수 =====
        시군구명
count   3196
unique    21
top      강남구
freq     715

 ===== test object컬럼 unique 수 =====
        시군구명
count   1476
unique    21
top      강남구
freq     330

 ===== train 결측치 수 =====
0

 ===== test 결측치 수 =====
0

 ===== target 기술 통계 =====
count     3196.000000
mean     10351.586483
std       1865.160521
min          0.000000
25%       9879.650000
50%      10673.150000
75%      11333.075000
max      13443.700000
Name: 총가스사용량, dtype: float64

In [ ]:
# 데이터
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/10_2/gas_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/10_2/gas_test.csv")

# 데이터 전처리
target = train.pop('총가스사용량')

# 원핫 인코딩
print(train.shape, test.shape)
train = pd.get_dummies(train)
test = pd.get_dummies(test)
print(train.shape, test.shape)


# 검증데이터 분리
from sklearn.model_selection import train_test_split
X_tr, X_val, y_tr, y_val = train_test_split(train, target, test_size=0.2, random_state=0)

# 랜덤포레스트
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(random_state=0)
rf.fit(X_tr, y_tr)
pred = rf.predict(X_val)

# RMSE
from sklearn.metrics import root_mean_squared_error
print(root_mean_squared_error(y_val, pred))

# LightGBM
import lightgbm as lgb
lg = lgb.LGBMRegressor(random_state=0, verbose=-1)
lg.fit(X_tr, y_tr)
pred = lg.predict(X_val)
print(root_mean_squared_error(y_val, pred))

# 최종 제출 파일
pred = rf.predict(test)
result = pd.DataFrame({'pred':pred})
result.to_csv("result.csv", index=False)

(3196, 5) (1476, 5)
(3196, 25) (1476, 25)
960.485846380754
1064.8095758723994

### 심화(0 처리)

In [ ]:
# 데이터
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/10_2/gas_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/10_2/gas_test.csv")

# 데이터 전처리
cond = train['총가스사용량'] == 0
train = train[~cond]
target = train.pop('총가스사용량')

# 원핫 인코딩
train = pd.get_dummies(train)
test = pd.get_dummies(test)

# 검증데이터 분리
from sklearn.model_selection import train_test_split
X_tr, X_val, y_tr, y_val = train_test_split(train, target, test_size=0.2, random_state=0)

# 랜덤포레스트
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(random_state=0)
rf.fit(X_tr, y_tr)
pred = rf.predict(X_val)

# RMSE
from sklearn.metrics import root_mean_squared_error
print(root_mean_squared_error(y_val, pred))

# LightGBM
import lightgbm as lgb
lg = lgb.LGBMRegressor(random_state=0, verbose=-1)
lg.fit(X_tr, y_tr)
pred = lg.predict(X_val)
print(root_mean_squared_error(y_val, pred))

# 최종 제출 파일
pred = rf.predict(test)
result = pd.DataFrame({'pred':pred})
result.to_csv("result.csv", index=False)

673.8026644431536
741.9117749289708