## 작업형1

### 문제 1
제공된 데이터(subject_performance.csv)는 학생들이 각 문제를 풀었을 때의 정답 여부를 기록한 자료이다. 각 문제는 대주제와 소주제로 분류되어 있다. 아래 수행 순서에 따라 데이터를 처리한 뒤, 구한 값을 [제출 형식]에 맞춰 답안 페이지에 입력하시오.

제공 데이터
- major_topic : 대주제
- sub_topic : 소주제
- student_id : 학생 ID
- is_correct : 정답 여부(1: 정답, 0: 오답)

수행 순서
1. 소주제별 정답률을 계산한다.
    - 정답률 = (해당 소주제의 정답 개수) / (해당 소주제의 전체 문제 풀이 수)
2. 소주제들의 정답률 중 3번째로 높은 값을 구하시오.
    - 단, 정답률이 같은 경우 하나로 취급한다. 정답률이 0.7, 0.7, 0.6, 0.5인 경우, 세 번째로 높은 값은 0.5이다.

[제출형식] 반올림하여 소수 셋째 자리까지 작성

In [25]:
import pandas as pd
# 데이터 불러오기
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/10_1/subject_performance.csv")
df.head()

        major_topic             sub_topic  student_id  is_correct
0       Mathematics  Discrete Mathematics         359           1
1       Mathematics  Discrete Mathematics         621           1
2  Computer Science             Databases        1366           1
3       Mathematics  Discrete Mathematics        1377           0
4           Physics             Mechanics         535           0

In [30]:
df.groupby(["sub_topic","is_correct"]).count()

                                 major_topic  student_id
sub_topic            is_correct
Algorithms           0                    63          63
                     1                   233         233
Calculus             0                   105         105
                     1                   217         217
Databases            0                   110         110
                     1                   196         196
Discrete Mathematics 0                   104         104
                     1                   188         188
Electromagnetism     0                    99          99
                     1                   191         191
Linear Algebra       0                    63          63
                     1                   233         233
Mechanics            0                    83          83
                     1                   188         188
Operating Systems    0                    99          99
                     1                   191         191
Quantum              0                   100         100
                     1                   201         201

In [ ]:
# 방법1

# 1. 소주제별 정답률 계산 (정답1, 오답0)

# 2. 내림차순 정렬 후 중복 제거

#정답: 0.674

In [ ]:
# 방법2
# 1. 소주제별 정답률 계산 (정답1, 오답0)

# 2. 상위 4개 추출 후 중복 제거

#정답: 0.674

### 문제2

### 문제2
제공된 데이터(cafe_sales.csv)는 2024년 4월부터 2025년 12월까지의 카페 메뉴 판매 이력이다. 소문항을 각각 구한 다음 [제출 형식]에 맞춰 답안 페이지에 입력하시오.

제공 데이터
- order_date : 주문 날짜 (예 2024.05.24 13:22)
- category : 음료/디저트 종류 (예 coffee, tea …)
- item : 메뉴명
- price : 판매 금액

소문항

2-1. 연-월별 총 매출액을 계산하여 큰 순서대로 정렬했을 때, 2번째로 큰 매출액을 입력하시오.

2-2. 연-월별 총 매출액이 4번째로 큰 연-월을 찾으시오. 해당 연-월의 데이터에서 카테고리별 매출 합계를 계산하고, 그중 최댓값을 입력하시오.

[제출 형식] 정수로 작성

In [47]:
import pandas as pd

# 데이터 불러오기
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/10_1/cafe_sales.csv")
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_date  1000 non-null   object
 1   category    1000 non-null   object
 2   item        1000 non-null   object
 3   price       1000 non-null   int64
dtypes: int64(1), object(3)
memory usage: 31.4+ KB

         order_date  category      item  price
0  2025.03.08 23:30       tea  GreenTea   6861
1  2025.10.01 13:05    coffee     Latte   6080
2  2025.04.30 17:32  smoothie     Mango   6116
3  2025.12.07 06:45       tea  BlackTea   7807
4  2024.04.10 00:40   dessert    Cookie   7964

In [ ]:
# 2-1
# order_date → 연-월 변환
df["order_date"] = pd.to_datetime(df["order_date"])
# 2-1
# 1. 연-월 단위로 그룹화하여 각 월의 총 매출액(price 합계)을 계산
df["년도"] = df["order_date"].dt.year
df["월"] = df["order_date"].dt.month
# 정답: 328741

In [57]:
# 2. 연-월별 총매출액 중 상위 2개만 추출
df.groupby(["년도","월"])["price"].sum().sort_values(ascending = False)

년도    월
2025  3     347848
      7     328741
      5     311810
2024  10    309026
2025  8     308798
      10    305833
2024  5     303992
      7     300886
2025  6     292062
2024  4     291906
2025  4     284055
      9     277927
      2     276728
      11    262399
      12    261205
2024  8     241602
      12    237023
      9     230353
      6     230115
2025  1     211567
2024  11    210704
Name: price, dtype: int64

In [60]:
# 2-2

# 1. 연-월별 총매출액 중 상위 4개만 추출

# 2. 4번째로 큰 연-월에 해당하는 데이터만 추출
cond1 = df["년도"] == 2024
cond2 = df["월"] == 10
cond = (cond1&cond2)
tmp = df[cond]
tmp.groupby("category")["price"].sum().max()
# 3. 해당 연-월의 카테고리별 매출 합계 중 최댓값 계산

# 정답: 104660

104660

### 문제3

### 문제 3
제공된 데이터(hamspam.csv)는 문자 메시지 내용과 스팸 여부를 담고 있다.
아래 수행 순서에 따라 데이터를 처리한 뒤, 구한 값을 [제출 형식]에 맞춰 답안 페이지에 입력하시오.

제공 데이터
- label : 메시지 구분 (spam: 스팸, ham: 정상)
- text : 메시지

수행 순서
1. 각 메시지의 단어 개수를 띄어쓰기(공백) 기준으로 계산하시오.
2. 스팸 메시지의 평균 단어 개수와 정상 메시지의 평균 단어 개수를 각각 구하시오.
3. 두 평균의 차이의 절댓값을 구하여 입력하시오.

[제출형식] 반올림하여 소수 셋째 자리까지 작성

In [104]:
import pandas as pd

# 데이터 불러오기
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/10_1/hamspam.csv")
df.head()
df = df.values.tolist()

URLError: <urlopen error [Errno 11001] getaddrinfo failed>

In [103]:
tmp = []
for i,j in df:
    cnt = 0
    for i in j.split():
        cnt += 1
    tmp.append(cnt)
tmp

TypeError: cannot unpack non-iterable int object

In [89]:
tmp = pd.DataFrame(tmp)

In [92]:
df  = pd.DataFrame(df)

In [93]:
df.shape, tmp.shape

((2000, 2), (2000, 1))

In [101]:
help("df.concat()")

No Python documentation found for 'df.concat()'.
Use help() to get the interactive help utility.
Use help(str) for help on the str class.

In [ ]:
# 방법1
import pandas as pd
# 데이터 불러오기
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/10_1/hamspam.csv")

# 1. 각 메시지의 단어 개수 구하기 (띄어쓰기 기준)

# 체크 (2번째 행)

# 2. 스팸과 정상 메시지의 평균 단어 수 구하기

# 3. 두 평균 차이의 절댓값 구하기

# 4. 소수 셋째 자리까지 반올림

# 정답: 0.047

In [ ]:
# 방법2
import pandas as pd
# 데이터 불러오기
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/10_1/hamspam.csv")

# 1. 각 메시지의 단어 개수 구하기 (띄어쓰기 기준)

# 2. 스팸과 정상 메시지의 평균 단어 수 구하기

# 3. 두 평균 차이의 절댓값 구하기

# 4. 소수 셋째 자리까지 반올림

# 정답: 0.047

0.047