## 작업형1

### 문제 1
제공된 데이터(subject_performance.csv)는 학생들이 각 문제를 풀었을 때의 정답 여부를 기록한 자료이다. 각 문제는 대주제와 소주제로 분류되어 있다. 아래 수행 순서에 따라 데이터를 처리한 뒤, 구한 값을 [제출 형식]에 맞춰 답안 페이지에 입력하시오.

제공 데이터
- major_topic : 대주제
- sub_topic : 소주제
- student_id : 학생 ID
- is_correct : 정답 여부(1: 정답, 0: 오답)

수행 순서
1. 소주제별 정답률을 계산한다.
    - 정답률 = (해당 소주제의 정답 개수) / (해당 소주제의 전체 문제 풀이 수)
2. 소주제들의 정답률 중 3번째로 높은 값을 구하시오.
    - 단, 정답률이 같은 경우 하나로 취급한다. 정답률이 0.7, 0.7, 0.6, 0.5인 경우, 세 번째로 높은 값은 0.5이다.

[제출형식] 반올림하여 소수 셋째 자리까지 작성

In [2]:
import pandas as pd

# 데이터 불러오기
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/10_1/subject_performance.csv")
df = df.drop("major_topic",axis=1)

In [13]:
df.head()
a = df.groupby("sub_topic")["is_correct"].sum()

In [14]:
b = df.groupby("sub_topic")["is_correct"].count()

In [28]:
round(a/b,3).sort_values(ascending=False) #0.674

sub_topic
Algorithms              0.787
Linear Algebra          0.787
Mechanics               0.694
Calculus                0.674
Quantum                 0.668
Electromagnetism        0.659
Operating Systems       0.659
Discrete Mathematics    0.644
Databases               0.641
Name: is_correct, dtype: float64

### 문제2

### 문제2
제공된 데이터(cafe_sales.csv)는 2024년 4월부터 2025년 12월까지의 카페 메뉴 판매 이력이다. 소문항을 각각 구한 다음 [제출 형식]에 맞춰 답안 페이지에 입력하시오.

제공 데이터
- order_date : 주문 날짜 (예 2024.05.24 13:22)
- category : 음료/디저트 종류 (예 coffee, tea …)
- item : 메뉴명
- price : 판매 금액

소문항

2-1. 연-월별 총 매출액을 계산하여 큰 순서대로 정렬했을 때, 2번째로 큰 매출액을 입력하시오.

2-2. 연-월별 총 매출액이 4번째로 큰 연-월을 찾으시오. 해당 연-월의 데이터에서 카테고리별 매출 합계를 계산하고, 그중 최댓값을 입력하시오.

[제출 형식] 정수로 작성

In [78]:
import pandas as pd

# 데이터 불러오기
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/10_1/cafe_sales.csv")
df["order_date"] = pd.to_datetime(df["order_date"])
df["연"] = df["order_date"].dt.year
df["월"] = df["order_date"].dt.month

In [84]:
#df.groupby(["연","월"])["price"].sum().sort_values(ascending=False) # 328741

In [88]:
# 2024  10 
cond1 = df["연"] == 2024
cond2 = df["월"] == 10
df[cond1 & cond2].groupby("category")["price"].sum() # 104660

category
coffee       84799
dessert      65681
smoothie    104660
tea          53886
Name: price, dtype: int64

### 문제3

### 문제 3
제공된 데이터(hamspam.csv)는 문자 메시지 내용과 스팸 여부를 담고 있다.
아래 수행 순서에 따라 데이터를 처리한 뒤, 구한 값을 [제출 형식]에 맞춰 답안 페이지에 입력하시오.

제공 데이터
- label : 메시지 구분 (spam: 스팸, ham: 정상)
- text : 메시지

수행 순서
1. 각 메시지의 단어 개수를 띄어쓰기(공백) 기준으로 계산하시오.
2. 스팸 메시지의 평균 단어 개수와 정상 메시지의 평균 단어 개수를 각각 구하시오.
3. 두 평균의 차이의 절댓값을 구하여 입력하시오.

[제출형식] 반올림하여 소수 셋째 자리까지 작성

In [66]:
import pandas as pd

# 데이터 불러오기
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/10_1/hamspam.csv")
df.head()
# a = df["text"]

  label                                               text
0   ham  Incididunt tempor elit sit do aliqua eiusmod a...
1   ham       Adipiscing tempor lorem ipsum dolore tempor.
2  spam    Tempor tempor magna sed incididunt consectetur.
3   ham  Consectetur incididunt amet adipiscing amet lo...
4   ham                  Sit ipsum labore sit do sit elit.

In [60]:
a = a.str.split(" ")

In [68]:
tmp = []
for i in a:
    tmp.append(len(i))
temp = pd.DataFrame({
    "len" : tmp
})
df["len"] = temp

In [69]:
df

     label                                               text  len
0      ham  Incididunt tempor elit sit do aliqua eiusmod a...   10
1      ham       Adipiscing tempor lorem ipsum dolore tempor.    6
2     spam    Tempor tempor magna sed incididunt consectetur.    6
3      ham  Consectetur incididunt amet adipiscing amet lo...   12
4      ham                  Sit ipsum labore sit do sit elit.    7
...    ...                                                ...  ...
1995   ham  Lorem tempor aliqua dolor dolore tempor do lab...   15
1996  spam  Sit ut aliqua adipiscing incididunt sit consec...    8
1997  spam  Ipsum aliqua incididunt et dolore tempor eiusm...   12
1998   ham          Eiusmod do elit consectetur labore do do.    7
1999   ham  Sed sed lorem aliqua dolore labore do incididu...   12

[2000 rows x 3 columns]

In [ ]:
cond1 = df["label"] == "ham"
cond2 = df["label"] == "spam"

len    0.047106
dtype: float64

In [75]:
round(abs(df[cond1][["len"]].mean() - df[cond2][["len"]].mean()),3) # 0.047

len    0.047
dtype: float64