## 작업형1

### 문제1
1. 대륙('continent')별 맥주 소비량(‘beer_servings’)의 평균을 계산하고, 평균이 가장
 큰 대륙을 찾으시오.
2. 1번에서 찾은 대륙에서 맥주 소비량이 5번째로 많은 국가(‘country’)의 맥주 소비량을 구하시오.

In [1]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/8_1/drinks.csv")
df.head()

c:\Users\dnwpg\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,Asia
1,Albania,89,132,54,4.9,Europe
2,Algeria,25,0,14,0.7,Africa
3,Andorra,245,138,312,12.4,Europe
4,Angola,217,57,45,5.9,Africa

In [14]:
df.sort_values(by = "beer_servings",ascending=False).head() # Ireland - 313

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
45,Czech Republic,361,170,134,11.8,Europe
65,Germany,346,117,175,11.3,Europe
135,Poland,343,215,56,10.9,Europe
98,Lithuania,343,244,56,12.9,Europe
81,Ireland,313,118,165,11.4,Europe

### 문제2
1. ‘관광객비율’이 두 번째로 높은 국가의 ‘사업’ 방문객 수를 a라고 정의하시오.
2. ‘관광’이 두 번째로 높은 국가의 ‘공무’ 방문객 수를 b라고 정의하시오.
3. a와 b의 합을 구하시오.
- 방문객 합계 = 관광 + 공무 + 사업 + 기타
- 관광객 비율 = 관광 / 방문객 합계

In [46]:
# 방법1
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/8_1/tourist.csv")
df["방문자합계"] = df["관광"] + df["공무"] + df["사업"] + df["기타"]
df["관광객비율"] = df["관광"] / df["방문자합계"]
df.sort_values(by = "관광객비율", ascending = False).head() # 203
df.sort_values(by = "관광", ascending = False).head() # 238
ans = 203 + 238
ans

441

In [ ]:
# 방법2
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/8_1/tourist.csv")

### 문제3
1. 주어진 데이터에서 ‘co’와 ‘nmhc’ 컬럼을 각각 Min-Max 스케일링하시오.
2. 스케일링된 ‘co’, ‘nmhc’ 컬럼의 표준편차를 각각 구하시오.
3. ‘co’ 컬럼의 표준편차에서 ‘nmhc’ 컬럼의 표준편차를 뺀 값을 소수점 3자리로 반올림하여 구하시오.
- Min-Max 스케일링 = (X - min_X) / (max_X - min_X)
- X 변수의 최솟값: min_X
- X 변수의 최댓값: max_X

In [51]:
# 방법1
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/8_1/chem.csv")
df.head()

  sample   co  nmhc  etc
0    샘플1   79    54   31
1    샘플2   84    57   58
2    샘플3  109    74  113
3    샘플4   15    77   21
4    샘플5   65    77  115

In [52]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()
df["co"] = sc.fit_transform(df[["co"]])
df["nmhc"] = sc.fit_transform(df[["nmhc"]])

print(df["co"].std()-df["nmhc"].std())

-0.017410052346145344

In [ ]:
# 방법2
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/8_1/chem.csv")