## 작업형2 - 통신사에서 고객에게 청구될 총 금액을 예측하시오.
- 제공된 데이터 목록:
    - churn_train.csv(훈련 데이터)
    - churn_test.csv(평가용 데이터)
- 예측할 컬럼: TotalCharges(총 청구액)
- 학습용 데이터(churn_train.csv)를 이용하여 총 청구액을 예측하는 모델을 만든 후 이를 평가용 데이터(churn_test.csv)
에 적용해 얻은 예측값을 다음과 같은 형식의 CSV 파일로 생성하시오.

- 제출 파일은 다음 1개의 컬럼을 포함해야 한다.
    - pred: 예측된 총 청구액
    - 제출 파일명: ‘result.csv’
- 제출한 모델의 성능은 MAE(Mean Absolute Error) 평가지표에 따라 채점한다.

## 문제정의

In [ ]:
# 문제정의
# 평가: MAE
# target: TotalCharges
# 최종파일: result.csv(컬럼 1개 pred)

In [43]:
# 라이브러리 및 데이터 불러오기
import pandas as pd
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/8_2/churn_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/8_2/churn_test.csv")

print(train.shape,test.shape)

target = train.pop("TotalCharges")

(4116, 19) (1764, 18)

In [44]:
train = train.drop("customerID",axis = 1)
test = test.drop("customerID",axis = 1)

In [45]:
from sklearn.preprocessing import LabelEncoder
l = train.select_dtypes(include="object").columns
for i in l:
    le = LabelEncoder()
    train[i] = le.fit_transform(train[i])
    test[i] = le.transform(test[i])

train.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod
0,1,0,0,0,7,1,2,2,1,1,1,1,1,1,2,0,2
1,0,1,0,1,53,0,1,1,2,2,0,2,2,2,0,0,1
2,0,1,0,1,68,0,1,0,2,2,2,0,0,2,0,0,3
3,1,1,0,1,44,0,1,2,1,1,1,1,1,1,0,1,1
4,1,0,1,0,7,1,2,1,0,2,2,0,2,0,1,0,2

In [46]:
from sklearn.model_selection import train_test_split
x_tr,x_val,y_tr,y_val = train_test_split(train,target,test_size = 0.2, random_state=0)
x_tr

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod
2312,1,0,1,1,24,0,1,2,1,1,1,1,1,1,1,1,1
1523,0,0,0,0,36,1,2,2,1,1,1,1,1,1,1,0,1
3950,1,1,0,0,64,1,2,0,2,2,2,0,0,2,2,0,0
3265,1,1,0,1,42,1,2,0,0,2,2,2,2,2,2,1,3
461,0,0,1,1,50,0,1,1,0,0,2,0,0,0,0,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1033,1,0,0,0,22,0,1,0,0,2,2,2,0,0,0,0,2
3264,1,0,0,1,37,1,0,2,1,1,1,1,1,1,0,0,2
1653,1,1,0,0,44,1,0,1,0,0,0,2,2,2,1,0,2
2607,1,1,0,0,44,0,1,0,2,0,2,0,0,0,1,1,2
2732,0,1,1,1,17,1,2,1,0,2,2,0,0,0,2,0,2

In [47]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(random_state=0)
model = rf.fit(x_tr,y_tr)
pred = model.predict(x_val)

import lightgbm as lgb
ll = lgb.LGBMRegressor(random_state=0,verbose=-1)
model1 = ll.fit(x_tr,y_tr)
pred1 = model.predict(x_val)

In [48]:
from sklearn.metrics import median_absolute_error
a = median_absolute_error(y_val,pred)
b = median_absolute_error(y_val,pred1)

print(a,b)

739.8873000000001 739.8873000000001

In [49]:
ans = model.predict(test)
a = pd.DataFrame({
    "pred" : ans
})
a

           pred
0     3707.6212
1      923.7132
2     4057.4078
3      952.6143
4     1322.1638
...         ...
1759   304.8777
1760  4085.7944
1761  4509.4186
1762   988.5564
1763  3491.2195

[1764 rows x 1 columns]