## 작업형3

## 문제1

### 문제1-1
주어진 데이터에서 로지스틱 회귀 분석을 수행해 유의확률(p-value)이 0.05 이상인 유의하지 않은 독립변수의 개수를 구하시오. (종속변수: Churn)

In [31]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/8_3/churn.csv")
df.head()

,Churn,AccountWeeks,ContractRenewal,DataPlan,DataUsage,CustServCalls,DayMins,DayCalls,MonthlyCharge,OverageFee,RoamMins
0,0,51,1,0,1.0,0,303.7,83,72.5,9.3,3.8
1,1,61,1,0,-0.2,2,194.8,89,66.3,10.9,13.3
2,0,84,1,1,-1.3,2,157.6,109,35.7,10.0,12.5
3,0,65,1,0,1.0,1,223.1,129,64.2,9.1,5.1
4,0,154,1,0,1.0,0,137.0,115,40.0,7.7,4.6

In [34]:
from statsmodels.formula.api import logit
model = logit("Churn ~ AccountWeeks + ContractRenewal + DataPlan + DataUsage + CustServCalls + DayMins + DayCalls + MonthlyCharge + OverageFee + RoamMins",df).fit()
model.pvalues[1:] > 0.05 #8

Optimization terminated successfully.
         Current function value: 0.393603
         Iterations 6

AccountWeeks        True
ContractRenewal     True
DataPlan            True
DataUsage          False
CustServCalls       True
DayMins            False
DayCalls            True
MonthlyCharge       True
OverageFee          True
RoamMins            True
dtype: bool

### 문제1-2
유의확률(p-value)이 0.05 미만인 유의한 변수만을 사용해 다시 로지스틱 회귀 분석을 수행하시오. 이 회귀식의 유의한 회귀 계수(상수항 포함)의 합계를 구하시오. (반올림하여 소수 셋째 자리까지 계산)

In [39]:
from statsmodels.formula.api import logit
model = logit("Churn ~ DataUsage + DayMins",df).fit()
round(model.params.sum(),3)

Optimization terminated successfully.
         Current function value: 0.397599
         Iterations 6

-1.213

### 문제1-3
문제 1-2에서 수행한 로지스틱 회귀식에서 ‘DataUsage’ 변수가 5만큼 증가할 때 오즈비(Odds Ratio)를
구하시오. (반올림하여 소수 셋째 자리까지 계산)

In [40]:
import numpy as np
np.exp(model.params["DataUsage"]*5)

0.42798312548416284

## 문제2

### 문제2-1
주어진 데이터를 이용해 종속변수(PIQ)와 독립변수(Brain, Height, Weight)로 다중 선형 회귀 분석을 수행
하시오. 이때 유의확률(p-value)이 가장 작은 변수의 회귀 계수 값을 구하시오. (반올림하여 소수 셋째 자리까지 계산)

In [23]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/8_3/piq.csv")
df.head()

   PIQ  Brain  Height  Weight
0  132  85.78    62.5     127
1   96  86.54    68.0     135
2   84  90.49    66.3     134
3  134  79.06    62.0     122
4   86  88.91    70.0     180

In [26]:
from statsmodels.formula.api import ols
model = ols("PIQ ~ Brain + Height + Weight",df).fit()
model.params["Brain"]

2.3431301009511682

### 문제 2-2
문제 2-1에 적합한 모델의 결정 계수(R-squared) 값을 구하시오. (반올림하여 소수 둘째 자리까지 계산)

In [28]:
model.rsquared

0.3704738038416522

### 문제 2-3
뇌 크기(Brain)가 90, 키(Height)가 70, 몸무게(Weight)가 150일 때의 PIQ를 예측하시오. (반올림하여 정수로 계산)

In [29]:
new_data = pd.DataFrame({
    "Brain" : [90],
    "Height" : [70],
    "Weight" : [150]
})
new_data

   Brain  Height  Weight
0     90      70     150

In [30]:
model.predict(new_data)

0    106.38302
dtype: float64