# Section5

In [9]:
import pandas as pd

train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p2/drug_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p2/drug_test.csv")

In [10]:
train.shape,test.shape

((80, 6), (100, 5))

In [13]:
target = train["Drug"]
train = train.drop("Drug",axis=1)
train.head()

   Age Sex      BP Cholesterol  Na_to_K
0   33   F     LOW        HIGH   33.486
1   31   M    HIGH      NORMAL   11.871
2   68   F    HIGH      NORMAL   10.189
3   39   M    HIGH        HIGH    9.664
4   51   F  NORMAL        HIGH   13.597

In [14]:
test.head()

   Age Sex      BP Cholesterol  Na_to_K
0   74   F     LOW        HIGH   20.942
1   65   M    HIGH      NORMAL   34.997
2   58   F     LOW        HIGH   38.247
3   34   M  NORMAL        HIGH   22.456
4   59   M    HIGH        HIGH   13.935

In [15]:
cols = train.select_dtypes(include=["O"]).columns
from sklearn.preprocessing import LabelEncoder
for col in cols:
    le = LabelEncoder()
    train[col] = le.fit_transform(train[col])
    test[col] = le.transform(test[col])

In [25]:
from sklearn.model_selection import train_test_split
x_tr,x_val,y_tr,y_val = train_test_split(
    train,
    target,
    test_size = 0.2,
    random_state = 0
)
x_tr.shape, y_tr.shape

((64, 9), (64,))

In [26]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(x_tr,y_tr)
pred = rf.predict(x_val)

from sklearn.metrics import f1_score
tmp = f1_score(y_val,pred, average="macro")
print(tmp)

0.8809523809523809

In [27]:
pred = rf.predict(test)
pred

array(['DrugY', 'DrugY', 'DrugY', 'DrugY', 'drugA', 'drugC', 'drugA',
       'DrugY', 'drugX', 'drugX', 'DrugY', 'DrugY', 'drugX', 'DrugY',
       'drugX', 'DrugY', 'drugA', 'drugA', 'drugA', 'DrugY', 'DrugY',
       'drugA', 'drugX', 'DrugY', 'DrugY', 'drugC', 'DrugY', 'drugC',
       'drugA', 'DrugY', 'DrugY', 'DrugY', 'DrugY', 'drugA', 'drugC',
       'DrugY', 'drugX', 'drugX', 'DrugY', 'DrugY', 'DrugY', 'drugA',
       'drugB', 'drugA', 'drugA', 'drugA', 'DrugY', 'DrugY', 'DrugY',
       'DrugY', 'DrugY', 'drugX', 'drugX', 'drugX', 'drugX', 'drugA',
       'drugA', 'drugB', 'DrugY', 'drugX', 'DrugY', 'DrugY', 'DrugY',
       'DrugY', 'drugC', 'drugX', 'drugX', 'DrugY', 'DrugY', 'DrugY',
       'drugX', 'drugX', 'drugC', 'drugX', 'drugC', 'drugC', 'DrugY',
       'drugA', 'DrugY', 'DrugY', 'DrugY', 'drugB', 'DrugY', 'DrugY',
       'DrugY', 'drugX', 'DrugY', 'drugX', 'DrugY', 'DrugY', 'drugC',
       'drugX', 'DrugY', 'DrugY', 'drugX', 'drugX', 'drugC', 'DrugY',
       'DrugY', 'drugX'], dtype=object)

In [28]:
ans = pd.DataFrame({
    "pred" : pred
})
ans

     pred
0   DrugY
1   DrugY
2   DrugY
3   DrugY
4   drugA
..    ...
95  drugX
96  drugC
97  DrugY
98  DrugY
99  drugX

[100 rows x 1 columns]

In [30]:
ans.to_csv("result.csv",index=False)

In [23]:
# 1. 문제정의
# 평가: f1-macro
# target: Drug
# 최종파일: result.csv(컬럼 1개 pred, 1확률값)

# 2. 라이브러리 및 데이터 불러오기
import pandas as pd

train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p2/drug_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p2/drug_test.csv")

# 3. 탐색적 데이터 분석(EDA)
print("===== 데이터 정보(자료형) =====")
print(train.info())

print("\n ===== train 결측치 수 =====")
print(train.isnull().sum().sum())

print("\n ===== test 결측치 수 =====")
print(test.isnull().sum().sum())

print("\n ===== train/test 카테고리별 수 =====")
print(train[['Sex', 'BP', 'Cholesterol']].nunique())
print(test[['Sex', 'BP', 'Cholesterol']].nunique())

print("\n ===== target 빈도 =====")
print(train['Drug'].value_counts())

===== 데이터 정보(자료형) =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Age          80 non-null     int64
 1   Sex          80 non-null     object
 2   BP           80 non-null     object
 3   Cholesterol  80 non-null     object
 4   Na_to_K      80 non-null     float64
 5   Drug         80 non-null     object
dtypes: float64(1), int64(1), object(4)
memory usage: 3.9+ KB
None

 ===== train 결측치 수 =====
0

 ===== test 결측치 수 =====
0

 ===== train/test 카테고리별 수 =====
Sex            2
BP             3
Cholesterol    2
dtype: int64
Sex            2
BP             3
Cholesterol    2
dtype: int64

 ===== target 빈도 =====
Drug
DrugY    32
drugX    27
drugA    13
drugB     6
drugC     2
Name: count, dtype: int64

In [24]:
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p2/drug_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p2/drug_test.csv")

# 4. 데이터 전처리
# 원핫인코딩
target = train.pop('Drug')
train = pd.get_dummies(train)
test = pd.get_dummies(test)

# 5. 검증 데이터 분할
from sklearn.model_selection import train_test_split
X_tr, X_val, y_tr, y_val = train_test_split(train, target, test_size=0.2, random_state=5)

# 6. 머신러닝 학습 및 평가
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=0)
rf.fit(X_tr, y_tr)
pred = rf.predict(X_val)

from sklearn.metrics import f1_score
f1 = f1_score(y_val, pred, average='macro')
print('\n f1-macro:', f1)

# 7. 예측 및 결과 파일 생성
pred = rf.predict(test)
submit = pd.DataFrame({'pred':pred})
submit.to_csv("result.csv", index=False)

 f1-macro: 0.7222222222222222