## Q. [마케팅] 자동차 시장 세분화
- 자동차 회사는 새로운 전략을 수립하기 위해 4개의 시장으로 세분화했습니다.
- 기존 고객 분류 자료를 바탕으로 신규 고객이 어떤 분류에 속할지 예측해주세요!


- 예측할 값(y): "Segmentation" (1,2,3,4)
- 평가: Macro f1-score
- data: train.csv, test.csv
- 제출 형식:
~~~
ID,Segmentation
458989,1
458994,2
459000,3
459003,4
~~~

### 답안 제출 참고
- 아래 코드 예측변수와 수험번호를 개인별로 변경하여 활용
- pd.DataFrame({'ID': test.ID, 'Segmentation': pred}).to_csv('003000000.csv', index=False)

### 노트북 구분
- basic: 수치형 데이터만 활용 -> 학습 및 test데이터 예측
- intermediate: 범주형 데이터도 활용 -> 학습 및 test데이터 예측
- advanced: 학습 및 교차 검증(모델 평가) -> 하이퍼파라미터 튜닝 -> test데이터 예측

In [1]:
# 라이브러리 불러오기
import pandas as pd

c:\Users\dnwpg\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
# 데이터 불러오기
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/4_2/train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/4_2/test.csv")

In [3]:
train.shape, test.shape

((6665, 11), (2154, 10))

In [4]:
target = train.pop("Segmentation")

In [6]:
ID = test.pop("ID")

In [23]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2154 entries, 0 to 2153
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           2154 non-null   int32
 1   Ever_Married     2154 non-null   int32
 2   Age              2154 non-null   int64
 3   Graduated        2154 non-null   int32
 4   Profession       2154 non-null   int32
 5   Work_Experience  2154 non-null   float64
 6   Spending_Score   2154 non-null   int32
 7   Family_Size      2154 non-null   int64
 8   Var_1            2154 non-null   int32
dtypes: float64(1), int32(6), int64(2)
memory usage: 101.1 KB

In [9]:
train = train.drop("ID",axis=1)

In [10]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6665 entries, 0 to 6664
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           6665 non-null   object
 1   Ever_Married     6665 non-null   object
 2   Age              6665 non-null   int64
 3   Graduated        6665 non-null   object
 4   Profession       6665 non-null   object
 5   Work_Experience  6665 non-null   float64
 6   Spending_Score   6665 non-null   object
 7   Family_Size      6665 non-null   float64
 8   Var_1            6665 non-null   object
dtypes: float64(2), int64(1), object(6)
memory usage: 468.8+ KB

In [11]:
train.isnull().sum()

Gender             0
Ever_Married       0
Age                0
Graduated          0
Profession         0
Work_Experience    0
Spending_Score     0
Family_Size        0
Var_1              0
dtype: int64

In [12]:
test.isnull().sum()

Gender             0
Ever_Married       0
Age                0
Graduated          0
Profession         0
Work_Experience    0
Spending_Score     0
Family_Size        0
Var_1              0
dtype: int64

In [20]:
from sklearn.preprocessing import LabelEncoder
l = ["Gender","Ever_Married","Graduated","Profession","Spending_Score","Family_Size","Var_1"]
for i in l:
    le = LabelEncoder()
    train[i] = le.fit_transform(train[i])
    test[i] = le.transform(test[i])
train.head()

,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Var_1
0,1,0,22,0,5,1.0,2,3,3
1,0,1,67,1,2,1.0,2,0,5
2,1,1,67,1,7,0.0,1,1,5
3,1,1,56,0,0,0.0,0,1,5
4,1,0,32,1,5,1.0,2,2,5

In [24]:
from sklearn.model_selection import train_test_split
x_tr,x_val,y_tr,y_val = train_test_split(
    train,
    target,
    test_size = 0.2,
    random_state = 0
)

In [44]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state = 42, max_depth = 200,n_estimators = 300)
model = rf.fit(x_tr,y_tr)
pred = model.predict(x_val)
pred

array([4, 2, 1, ..., 2, 3, 4], dtype=int64)

In [45]:
from sklearn.metrics import f1_score
ans = f1_score(y_val,pred, average = "macro")
ans

0.5038904257246398

In [46]:
ans = model.predict(test)

In [52]:
import pandas as pd
result = pd.DataFrame({
    "ID" : ID,
    "Segmentation" : ans
})
result

          ID  Segmentation
0     458989             2
1     458994             3
2     459000             3
3     459003             3
4     459005             1
...      ...           ...
2149  467950             1
2150  467954             4
2151  467958             2
2152  467961             3
2153  467968             4

[2154 rows x 2 columns]

In [53]:
result.to_csv("result.csv",index=False)