## 작업형1 문제
1-1. age 컬럼의 3사분위수와 1사분위수의 차를 절대값으로 구하고, 소수점 버려서, 정수로 출력

In [3]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/4_1/basic1.csv")
a = df["age"].quantile(0.25)
b = df["age"].quantile(0.75)
ans = int(abs((b-a)))
ans

50

1-2.(loves반응+wows반응)/(reactions반응) 비율이 0.4보다 크고 0.5보다 작으면서, type 컬럼이 'video'인 데이터의 갯수

In [9]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/4_1/fb.csv")
df.head()
tmp = (df["loves"] + df["wows"])/df["reactions"]
cond1 =  tmp > 0.4
cond2 = tmp < 0.5
cond3 = df["type"] == "video"
df[cond1&cond2&cond3]

,id,type,reactions,comments,shares,likes,loves,wows,hahas,sads,angrys
3116,3117,video,255,926,181,142,108,0,5,0,0
4624,4625,video,1397,771,695,765,485,139,4,1,3
4776,4777,video,259,695,263,151,106,0,2,0,0
4793,4794,video,146,303,221,73,69,2,1,0,1
4812,4813,video,184,530,224,101,80,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...
6308,6309,video,416,5352,580,204,194,3,13,1,1
6311,6312,video,370,6316,633,182,166,2,17,3,0
6335,6336,video,236,5237,526,138,97,1,0,0,0
6371,6372,video,239,2574,419,140,95,1,2,1,0
6701,6702,video,517,5514,388,243,220,8,43,3,0

1-3. date_added가 2018년 1월 이면서 country가 United Kingdom 단독 제작인 데이터의 갯수

In [ ]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/4_1/nf.csv")
df["date_added"] = pd.to_datetime(df["date_added"])
df["년도"] = (df["date_added"].dt.year)
df["월"] = (df["date_added"].dt.month)
cond1 = df["년도"] == 2018
cond2 = df["월"] == 1
cond3 = df["country"] == "United Kingdom"
df[cond1&cond2&cond3].reset_index()
# 6개

,index,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,년도,월
0,5057,s5058,TV Show,Retribution,NaN,"Georgina Campbell, Joe Dempsie, Adrian Edmonds...",United Kingdom,2018-01-30,2016,TV-MA,1 Season,"British TV Shows, Crime TV Shows, Internationa...",2018.0,1.0
1,5074,s5075,Movie,Bad Day for the Cut,Chris Baugh,"Nigel O'Neill, Susan Lynch, Józef Pawlowski, S...",United Kingdom,2018-01-18,2017,TV-MA,99 min,"Independent Movies, International Movies, Thri...",2018.0,1.0
2,5097,s5098,TV Show,Lovesick,NaN,"Johnny Flynn, Antonia Thomas, Daniel Ings, Han...",United Kingdom,2018-01-01,2018,TV-MA,3 Seasons,"British TV Shows, International TV Shows, Roma...",2018.0,1.0
3,7398,s7399,Movie,Manolo: The Boy Who Made Shoes for Lizards,Michael Roberts,"Manolo Blahnik, Anna Wintour, André Leon Talle...",United Kingdom,2018-01-15,2017,TV-MA,89 min,"Documentaries, International Movies",2018.0,1.0
4,8357,s8358,TV Show,The Inbetweeners,NaN,"Simon Bird, James Buckley, Blake Harrison, Joe...",United Kingdom,2018-01-01,2010,TV-MA,3 Seasons,"British TV Shows, TV Comedies",2018.0,1.0
5,8619,s8620,Movie,Treasures from the Wreck of the Unbelievable,Sam Hobkinson,NaN,United Kingdom,2018-01-01,2017,TV-G,82 min,"Documentaries, Dramas, International Movies",2018.0,1.0

## 작업형1 풀이
1-1. age 컬럼의 3사분위수와 1사분위수의 차를 절대값으로 구하고, 소수점 버려서, 정수로 출력

In [ ]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/4_1/basic1.csv")
# print("1사분위: ",df['age'].quantile(0.25))
# print("3사분위: ",df['age'].quantile(0.75))

result = abs(df['age'].quantile(0.25) - df['age'].quantile(0.75))
# print("절대값 차이: ",result)

print(int(result))

50

1-2.(loves반응+wows반응)/(reactions반응) 비율이 0.4보다 크고 0.5보다 작으면서, status_type=='video'인 데이터의 갯수

In [ ]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/4_1/fb.csv")
cond1 = (df['loves'] + df['wows'])/ df['reactions'] > 0.4
cond2 = (df['loves'] + df['wows'])/ df['reactions'] < 0.5
cond3 = df['type'] == 'video'

print(len(df[cond1 & cond2 & cond3]))

90

1-3. date_added가 2018년 1월 이면서 country가 United Kingdom 단독 제작인 데이터의 갯수¶

In [ ]:
# 풀이1 datatime 활용1
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/4_1/nf.csv")

cond1 = df['country'] == "United Kingdom"

df['date_added'] = pd.to_datetime(df['date_added'])
df['year'] = df['date_added'].dt.year
df['month'] = df['date_added'].dt.month


cond2 = df['year'] == 2018
cond3 = df['month'] == 1

print(len(df[cond1 & cond2 & cond3]))

6

In [ ]:
# 풀이2 datatime 활용2
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/4_1/nf.csv")

cond1 = df['country'] == "United Kingdom"

df['date_added'] = pd.to_datetime(df['date_added'])

cond2 = df['date_added'] >= '2018-1-1'
cond3 = df['date_added'] <= '2018-1-31'

print(len(df[cond1 & cond2 & cond3]))

6

In [ ]:
# 풀이3 datatime + between 활용
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/4_1/nf.csv")

cond1 = df['country'] == "United Kingdom"
df['date_added'] = pd.to_datetime(df['date_added'])
cond2 = df['date_added'].between('2018-1-1', '2018-1-31')
print(len(df[cond1 & cond2]))

6

In [ ]:
# 풀이4
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/4_1/nf.csv")

cond1 = df['country'] == "United Kingdom"

df['date_added'] = df['date_added'].fillna("")

str1 = "2018"
str2 = "January"
cond2 = df['date_added'].str.contains(str1)
cond3 = df['date_added'].str.contains(str2)

print(len(df[cond1 & cond2 & cond3]))

6

(추가 문제) 4. 만약 'country'컬럼에 대소문자 함께 있고, 띄어쓰기가 있는 것도 있고 없는 것도 있다면?

In [ ]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/4_1/nf.csv")

# 띄어쓰기 제거
df['country'] = df['country'].str.replace(' ','')

# 소문자로 변경
df['country'] = df['country'].str.lower()
df['country']

cond1 = df['country'] == "unitedkingdom"

df['date_added'] = pd.to_datetime(df['date_added'])
df['year'] = df['date_added'].dt.year
df['month'] = df['date_added'].dt.month


cond2 = df['year'] == 2018
cond3 = df['month'] == 1

print(len(df[cond1 & cond2 & cond3]))

6