# Section1

In [22]:
import pandas as pd
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p2/diabetes_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p2/diabetes_test.csv")

In [23]:
print(train.shape, test.shape)

(614, 9) (154, 8)

In [24]:
train.head(2)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,1,118,58,36,94,33.3,0.261,23,0
1,3,173,78,39,185,33.8,0.970,31,1

In [25]:
test.head(2)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,3,102,74,0,0,29.5,0.121,32
1,5,104,74,0,0,28.8,0.153,48

In [27]:
## 데이터 분리
target = train.pop("Outcome")
from sklearn.model_selection import train_test_split
x_tr,x_val,y_tr,y_val = train_test_split(
    train,
    target,
    test_size = 0.1,
    random_state = 0
)
x_tr

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
406,4,131,68,21,166,33.1,0.160,28
17,3,116,74,15,105,26.3,0.107,24
427,6,144,72,27,228,33.9,0.255,40
21,5,124,74,0,0,34.0,0.220,38
460,7,119,0,0,0,25.2,0.209,37
...,...,...,...,...,...,...,...,...
277,5,144,82,26,285,32.0,0.452,58
9,1,121,78,39,74,39.0,0.261,28
359,0,101,64,17,0,21.0,0.252,21
192,0,131,88,0,0,31.6,0.743,32
559,2,84,50,23,76,30.4,0.968,21

In [29]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state = 0)
rf.fit(x_tr,y_tr)
pred_proba = rf.predict_proba(x_val)

In [32]:
from sklearn.metrics import roc_auc_score
a = roc_auc_score(y_val,pred_proba[:,1])

In [33]:
a

0.8148148148148148

In [35]:
b = rf.predict_proba(test)
submit = pd.DataFrame({
    "pred" : b[:,1]
})
submit

     pred
0    0.28
1    0.30
2    0.07
3    0.00
4    0.10
..    ...
149  0.55
150  0.23
151  0.09
152  0.66
153  0.50

[154 rows x 1 columns]

In [37]:
submit.to_csv("ans.csv",index=False)

In [40]:
c = pd.read_csv("ans.csv")
c

     pred
0    0.28
1    0.30
2    0.07
3    0.00
4    0.10
..    ...
149  0.55
150  0.23
151  0.09
152  0.66
153  0.50

[154 rows x 1 columns]

In [12]:
# 1. 문제정의
# 평가: roc-auc
# target: Outcome
# 최종파일: result.csv(컬럼 1개 pred, 1확률값)

# 2. 라이브러리 및 데이터 불러오기
import pandas as pd
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p2/diabetes_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p2/diabetes_test.csv")

# 3. 탐색적 데이터 분석(EDA)
print("===== 데이터 크기 =====")
print("Train Shape:", train.shape)
print("Test Shape:", test.shape)
print("\n") # 줄 바꿈

print("===== train 데이터 샘플 =====")
print(train.head(1))
print("\n")

print("===== test 데이터 샘플 =====")
print(test.head(1))
print("\n")

print("===== 데이터 정보(자료형) =====")
print(train.info())
print("\n")

print("===== train 결측치 수 =====")
print(train.isnull().sum().sum())
print("\n")

print("===== test 결측치 수 =====")
print(test.isnull().sum().sum())
print("\n")

print("===== target 빈도 =====")
print(train['Outcome'].value_counts())

===== 데이터 크기 =====
Train Shape: (614, 9)
Test Shape: (154, 8)


===== train 데이터 샘플 =====
   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            1      118             58             36       94  33.3

   DiabetesPedigreeFunction  Age  Outcome
0                     0.261   23        0


===== test 데이터 샘플 =====
   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            3      102             74              0        0  29.5

   DiabetesPedigreeFunction  Age
0                     0.121   32


===== 데이터 정보(자료형) =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               614 non-null    int64
 1   Glucose                   614 non-null    int64
 2   BloodPressure             614 non-null    int64
 3   SkinThickness             614 non-null    int64
 4   Insulin                   614 non-null    int64
 5   BMI                       614 non-null    float64
 6   DiabetesPedigreeFunction  614 non-null    float64
 7   Age                       614 non-null    int64
 8   Outcome                   614 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 43.3 KB
None


===== train 결측치 수 =====
0


===== test 결측치 수 =====
0


===== target 빈도 =====
Outcome
0    403
1    211
Name: count, dtype: int64

In [13]:
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p2/diabetes_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p2/diabetes_test.csv")

# 4. 데이터 전처리
target = train.pop('Outcome')

# 5. 검증 데이터 분할
from sklearn.model_selection import train_test_split
X_tr, X_val, y_tr, y_val = train_test_split(train, target, test_size=0.2, random_state=0)

print("\n ===== 분할된 데이터 크기 =====")
print(X_tr.shape, X_val.shape, y_tr.shape, y_val.shape)

# 6. 머신러닝 학습 및 평가
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=0)
rf.fit(X_tr, y_tr)
pred = rf.predict_proba(X_val)

print("\n ===== 예측 결과 확인 (샘플 5개) =====")
print(pred[:5])

from sklearn.metrics import roc_auc_score
roc_auc = roc_auc_score(y_val, pred[:,1])
print('\n roc_auc:', roc_auc)

# 7. 예측 및 결과 파일 생성
pred = rf.predict_proba(test)
submit = pd.DataFrame({'pred':pred[:,1]})
submit.to_csv("result.csv", index=False)

 ===== 분할된 데이터 크기 =====
(491, 8) (123, 8) (491,) (123,)

 ===== 예측 결과 확인 (샘플 5개) =====
[[0.88 0.12]
 [0.29 0.71]
 [0.41 0.59]
 [0.75 0.25]
 [0.89 0.11]]

 roc_auc: 0.8002739726027398