## 일원 분산 분석

In [ ]:
import pandas as pd
# df = pd.read_csv("math.csv")
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part3/ch6/math.csv")
df.head()

    groups  scores
0  group_A      85
1  group_A      88
2  group_A      90
3  group_A      82
4  group_A      87

## 이원 분산 분석

In [ ]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p3/math.csv")
df.head()

    groups  scores
0  group_A      85
1  group_A      88
2  group_A      90
3  group_A      82
4  group_A      87

## 일원 분산 분석

In [ ]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p3/math.csv")

from scipy import stats

# 1. Shapiro-Wilk 검정 (정규성)
condA = df['groups']=='group_A'
print(stats.shapiro(df[condA]['scores']))

condB = df['groups']=='group_B'
print(stats.shapiro(df[condB]['scores']))

condC = df['groups']=='group_C'
print(stats.shapiro(df[condC]['scores']))

condD = df['groups']=='group_D'
print(stats.shapiro(df[condD]['scores']))

# 2. Levene 검정 (등분산성)
print(stats.levene(df[condA]['scores'], df[condB]['scores'], df[condC]['scores'], df[condD]['scores']))

ShapiroResult(statistic=np.float64(0.9715896670696531), pvalue=np.float64(0.9051800443853569))
ShapiroResult(statistic=np.float64(0.9499422438060351), pvalue=np.float64(0.6678172590861611))
ShapiroResult(statistic=np.float64(0.9299424104842702), pvalue=np.float64(0.44732595113862045))
ShapiroResult(statistic=np.float64(0.9065684572704982), pvalue=np.float64(0.25824165549017347))
LeveneResult(statistic=np.float64(1.757685352622062), pvalue=np.float64(0.17270284963232108))

In [ ]:
# 일원분산분석을 위한 모델 학습
from statsmodels.formula.api import ols
model = ols('scores ~ groups', df).fit()

# 3~9. ANOVA 테이블
from statsmodels.stats.anova import anova_lm
print(anova_lm(model))

            df  sum_sq     mean_sq          F        PR(>F)
groups     3.0   411.8  137.266667  34.174274  1.240642e-10
Residual  36.0   144.6    4.016667        NaN           NaN

[정답]
1. 0.9051811695098877,0.6678178906440735,0.44732627272605896,0.2582412362098694
2. 0.17270284963232108
3. 기각
4. 3
5. 36
6. 411.8
7. 137.266667
8. 34.174274
9. 1.240642e-10 (0.000000000124)

## 이원 분산 분석

In [ ]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p3/tomato2.csv")
print(df.head())

  비료유형  물주기  수확량
0    A    1  514
1    A    1  480
2    A    1  507
3    A    2  452
4    A    2  526

In [ ]:
import statsmodels.api as sm
from statsmodels.formula.api import ols

# 1~9 이원 분산 분석
model = ols('수확량 ~ C(비료유형) * C(물주기)', data=df).fit()
anova_table = sm.stats.anova_lm(model)
print(anova_table)

                  df        sum_sq      mean_sq         F    PR(>F)
C(비료유형)          2.0   5251.722222  2625.861111  3.184685  0.059334
C(물주기)           3.0   9057.000000  3019.000000  3.661490  0.026460
C(비료유형):C(물주기)   6.0   4271.833333   711.972222  0.863491  0.535426
Residual        24.0  19788.666667   824.527778       NaN       NaN

[정답]
1. 3.184685
2. 0.059334
3. 채택
4. 3.661490
5. 0.026460
6. 기각
7. 0.863491
8. 0.535426
9. 채택