## 작업형1

### 문제1

1. 총대출액은 신용대출과 담보대출의 합이다.
2. 각 지역코드 내에서, 성별(예: 1과 2)별로 '총대출액'의 합계를 계산하시오.
3. 성별 간 총대출액의 차이가 가장 큰 지역코드를 구하시오.

In [106]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/9_1/loan.csv")
df.head()

         지역코드  성별    신용대출     담보대출
0  4100000000   1  688608  5706058
1  4100000000   2  611035  2260521
2  4100000001   1  125392  5946493
3  4100000001   2  239679  4711962
4  4100000002   1  623758  5411745

In [107]:
df["총대출액"] = df["신용대출"] + df["담보대출"]

In [104]:
df = df.groupby(["지역코드","성별"])["총대출액"].sum()

In [108]:
df.groupby(["지역코드","성별"])["총대출액"].sum().unstack()

성별                 1         2
지역코드
4100000000  22891981  18339609
4100000001  34197683  17595557
4100000002  13119017  21827691
4100000003  16549091  54654134
4100000004  26831399  56145359
...              ...       ...
4100000587   9050332  19445103
4100000588  47396699  36281031
4100000589  28256320  17797635
4100000590  16813363  23655928
4100000591  20674327  12204772

[592 rows x 2 columns]

In [55]:
df.iloc[556:600]

지역코드        성별
4100000278  1     72934984
            2     12605775
4100000279  1     15307032
            2     11036908
4100000280  1     16378479
            2     32592929
4100000281  1     45716626
            2     19141300
4100000282  1     39254699
            2     16355399
4100000283  1      4002572
            2      8016355
4100000284  1     28050875
            2     20893339
4100000285  1     34915498
            2     23035401
4100000286  1     17687663
            2      6926584
4100000287  1     27609812
            2     18774234
4100000288  1     38490904
            2     18880282
4100000289  1     12845328
            2      4716503
4100000290  1     16062198
            2     22616042
4100000291  1     46716672
            2     41574738
4100000292  1     34434831
            2     23424363
4100000293  1     36329966
            2     13801520
4100000294  1     19595540
            2     18937161
4100000295  1     44036036
            2      8136264
4100000296  1     17406305
            2     19578059
4100000297  1     22680287
            2      9376010
4100000298  1     25567942
            2     27749028
4100000299  1     24618584
            2     14906828
Name: 총대출액, dtype: int64

In [34]:
tmp = []
for i in range(0,len(df),2):
    tmp.append([(df.iloc[i] - df.iloc[i+1]),i])

In [ ]:
# 4100000278

### 문제2

1. 검거율은 검거건수 / 발생건수이다.
2. 각 연도에서 가장 높은 검거율을 기록한 범죄유형을 찾으시오.
3. 해당 범죄유형의 검거건수를 구한 후, 이 값들을 모두 합산하시오. (정수로 구하시오)

In [110]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/9_1/crime.csv")
df.head(2)

,연도,구분,강력범죄,절도범죄,폭력범죄,지능범죄,풍속범죄,특별경제범죄,마약범죄,보건범죄,환경범죄,교통범죄,노동범죄,선거범죄,병역범죄,기타범죄
0,2014,발생건수,800,900,750,650,700,1034,600,850,800,900,750,800,700,1000
1,2014,검거건수,500,600,400,450,400,961,350,500,450,550,400,450,400,600

In [111]:
cond1 = df['구분'] == "발생건수"
cond2 = df['구분'] == "검거건수"
df1 = df[cond1].iloc[:, 2:]
df2 = df[cond2].iloc[:, 2:]

In [112]:
df1 = df1.reset_index(drop=True)
df2 = df2.reset_index(drop=True)

df3 = df2/df1
df3

,강력범죄,절도범죄,폭력범죄,지능범죄,풍속범죄,특별경제범죄,마약범죄,보건범죄,환경범죄,교통범죄,노동범죄,선거범죄,병역범죄,기타범죄
0,0.625000,0.666667,0.533333,0.692308,0.571429,0.929400,0.583333,0.588235,0.562500,0.611111,0.533333,0.562500,0.571429,0.600000
1,0.666667,0.928385,0.625000,0.733333,0.571429,0.600000,0.588235,0.562500,0.611111,0.631579,0.562500,0.588235,0.533333,0.600000
2,0.588235,0.750000,0.922727,0.733333,0.571429,0.631579,0.555556,0.562500,0.588235,0.611111,0.533333,0.562500,0.571429,0.631579
3,0.600000,0.555556,0.588235,0.687500,0.533333,0.631579,0.928571,0.555556,0.550000,0.631579,0.562500,0.588235,0.533333,0.555556
4,0.931034,0.666667,0.588235,0.687500,0.533333,0.631579,0.555556,0.562500,0.588235,0.611111,0.533333,0.562500,0.571429,0.631579
5,0.600000,0.555556,0.588235,0.687500,0.533333,0.631579,0.555556,0.928571,0.550000,0.631579,0.562500,0.588235,0.533333,0.555556
6,0.600000,0.555556,0.588235,0.908667,0.533333,0.631579,0.555556,0.562500,0.588235,0.611111,0.533333,0.562500,0.571429,0.631579

In [113]:
listbox = df3.idxmax(axis=1)

In [114]:
listbox

0    특별경제범죄
1      절도범죄
2      폭력범죄
3      마약범죄
4      강력범죄
5      보건범죄
6      지능범죄
dtype: object

In [115]:
result = 0
for index, item in enumerate(listbox):
    result = result + df2.loc[index, item]
print(result)

7799

### 문제3

1. 만족도의 결측치는 만족도의 평균값으로 대체한다.
2. 근속연수의 결측치는 동일한 부서 및 성과등급에 해당하는 직원들의 평균 근속연수로 대체한다. (이때, 평균 근속연수는 소수점 이하를 절사하여 정수로 변환하여 사용)
3. 각 직원의 '연봉 / 근속연수' 값을 계산하여, 그 값이 세 번째로 큰 직원의 근속연수를 구하시오.
4. 각 직원의 '연봉 / 만족도' 값을 계산하여, 그 값이 두 번째로 큰 직원의 교육참가횟수를 구하시오.
5. (3)과 (4)의 값을 더한 결과를 구하시오. (정수로 구하시오)

In [92]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/9_1/hr.csv")
df

      사원번호         부서 성과등급         연봉  근속연수  교육참가횟수  만족도
0    E0001  Marketing    B   73200000  14.0       5  6.0
1    E0002         IR    A   95100000   3.0       4  9.0
2    E0003    Manager    B   44700000   5.0       2  8.0
3    E0004         IR    B  122100000  16.0       3  8.0
4    E0005         IR    C   66000000   NaN       4  8.0
..     ...        ...  ...        ...   ...     ...  ...
995  E0996    Finance    B   90400000  15.0       3  2.0
996  E0997         IR    C  147600000  12.0       5  5.0
997  E0998      Sales    C   95600000   4.0       4  9.0
998  E0999      Sales    C   94400000   8.0       6  1.0
999  E1000         IR    A   92400000   9.0       2  5.0

[1000 rows x 7 columns]

In [94]:
df["만족도"] = df["만족도"].fillna(df["만족도"].mean())

In [97]:
df.groupby(["부서","성과등급"])["근속연수"].mean().astype("int")

부서         성과등급
Finance    A       11
           B       10
           C        9
HR         A        9
           B        9
           C       10
IR         A       11
           B       10
           C       10
Manager    A       11
           B       10
           C       10
Marketing  A       11
           B       11
           C        9
Sales      A        8
           B        9
           C       11
Name: 근속연수, dtype: int32