## 작업형2
### 문제. 농작물에서 농약 검출 여부를 예측하시오.
-	제공된 데이터 목록:
    - farm_train.csv (훈련 데이터)
    - farm_test.csv (평가용 데이터)
-	예측할 컬럼: 농약검출여부 (0:미검출, 1:검출, 2:재검사 필요)

학습용 데이터(farm_train.csv)를 이용하여 농약 검출 여부를 예측하는 모델을 구축한 후, 이를 평가용 데이터(farm_test.csv)에 적용하여 예측 결과를 다음과 같은 형식의 CSV 파일로 생성하시오.

제출 파일은 다음 한 개의 컬럼을 포함해야 합니다.
- pred: 예측된 검출 여부
- 제출 파일명: 'result.csv'

모델의 성능은 macro F1 Score 평가지표에 따라 채점됩니다.
제출 CSV 파일은 result.csv 형태로 제출하시오.

~~~
pred
0
1
0
2
0
...
~~~

In [2]:
# 라이브러리 및 데이터 불러오기
import pandas as pd
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/9_2/farm_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/refs/heads/main/p4/9_2/farm_test.csv")
train.shape,test.shape

((4000, 9), (1000, 8))

In [3]:
target = train.pop("농약검출여부")
train.head()

           농업면적    연도  지역       비료사용량        비료잔여량 작물종류 토양유형 등급
0  20079.652837  2004  대구  407.985516   146.290507   보리   점토  C
1  73858.643204  2012  울산  221.229692  1967.333638    밀   점토  B
2  65718.150861  2012  강원  370.967205  2253.522610    쌀   점토  B
3  37366.182902  2005  광주  274.128236  1487.535265    쌀   양토  B
4  81515.151289  2007  충남  213.410655   683.306745    쌀   양토  B

In [4]:
# 연도지우기
train = train.drop("연도", axis=1)
test = test.drop("연도",axis=1)

In [5]:
from sklearn.preprocessing import LabelEncoder
l = train.select_dtypes(include = "O").columns
list(l)
for i in list(l):
    le = LabelEncoder()
    train[i] = le.fit_transform(train[i])
    test[i] = le.transform(test[i])
train.shape

(4000, 7)

In [6]:
from sklearn.model_selection import train_test_split
x_tr,x_val,y_tr,y_val = train_test_split(
    train,
    target,
    test_size = 0.2,
    random_state = 0
)
x_tr.shape

(3200, 7)

In [7]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=0)
model = rf.fit(x_tr,y_tr)
pred = model.predict(x_val)


from sklearn.metrics import f1_score
ans = f1_score(y_val,pred,average="macro")
ans


import lightgbm as lgb
lb = lgb.LGBMClassifier(random_state=0,verbose=-1)
model1 = lb.fit(x_tr,y_tr)
pred1 = model1.predict(x_val)


from sklearn.metrics import f1_score
ans1 = f1_score(y_val,pred1,average="macro")
ans, ans1

c:\Users\dnwpg\anaconda3\lib\site-packages\dask\dataframe\__init__.py:42: FutureWarning:
Dask dataframe query planning is disabled because dask-expr is not installed.

You can install it with `pip install dask[dataframe]` or `conda install dask`.
This will raise in a future version.

  warnings.warn(msg, FutureWarning)

(0.892847890938027, 0.9328203621473091)

In [42]:
AN = model.predict(test)
a = pd.DataFrame({
    "pred" : AN
})
a

     pred
0       2
1       0
2       0
3       2
4       0
..    ...
995     2
996     2
997     2
998     2
999     0

[1000 rows x 1 columns]