## 작업형3

## 문제 1

제공된 데이터(`elderly_health.csv`)는 보건소에서 수집한 건강 검진 데이터로,  
나이, 당뇨병 이력, 신체 활동 여부, 공복 혈당 등에 따른 노령층 여부(predicted)에 관한 자료이다.  

이 데이터를  
- **Train 데이터**: id 1 ~ 2000  
- **Test 데이터**: id 2001 ~ 2227  

로 나누어 로지스틱 회귀분석(Logistic Regression)을 수행하고, 제시된 소문항에 답하시오.

---

### 제공 데이터 (`elderly_health.csv`)

### 종속 변수 (타겟 변수)
- **predicted** : 노령층 여부  
  - 0 = 비노령층  
  - 1 = 노령층  

### 독립 변수 (설명 변수)
- **id** : 고객 번호  
- **age** : 나이  
- **diabetic** : 당뇨병 이력  
- **activity** : 신체 활동 여부  
- **glus_fast** : 공복 혈당  
- **bmi** : 체질량지수  
- **blood_pressure** : 혈압  


---

## 문제 1-1

Train 데이터에서 id 변수를 제외한 모든 변수를 활용하여 로지스틱 회귀분석(Logistic Regression)을 수행하시오.

`diabetic`이 'no'인 사람 대비 'yes'인 사람의 오즈비(Odds Ratio)를 구하시오.

- 반올림하여 소수 둘째 자리까지 작성

---

## 문제 1-2

위 모델에서 test 데이터 중 노령층일 확률이 가장 높은 사람의 `glus_fast`(공복 혈당) 값을 구하시오.

- 정수로 작성

---

## 문제 1-3

위 모델로 test 데이터를 예측한 후,  
확률이 0.2 초과인 사람을 노령층으로 분류했을 때 민감도(Sensitivity)를 구하시오.

- 반올림하여 소수 둘째 자리까지 작성

In [49]:
# 1-1
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bae-v3/main/part4/ch11/elderly_health.csv")
train,test = df.iloc[:2000], df.iloc[2000:]
train.shape,test.shape
train = train.drop("id",axis=1)

In [53]:
from statsmodels.formula.api import logit
model = logit("predicted ~ age+diabetic+activity+glus_fast+bmi+blood_pressure",train).fit()
# print(model.summary())
# `diabetic`이 'no'인 사람 대비 'yes'인 사람의 오즈비(Odds Ratio)를 구하시오.
import numpy as np
ans = np.exp(3.0138 )
ans

Optimization terminated successfully.
         Current function value: 0.486192
         Iterations 7

20.36463870569573

In [55]:
# 1-2
## 문제 1-2
# 위 모델에서 test 데이터 중 노령층일 확률이 가장 높은 사람의 `glus_fast`(공복 혈당) 값을 구하시오.
# - 정수로 작성
pred = model.predict(test)
a = pred.idxmax()
a

2152

In [56]:
test.loc[a]

id                2153
age                 78
diabetic           pre
activity            no
glus_fast          181
bmi               26.3
blood_pressure     115
predicted            1
Name: 2152, dtype: object

In [28]:
# # 1-3
pred_labels = (pred > 0.2).astype(int)
actual_labels = test["predicted"]
from sklearn.metrics import recall_score
ans = recall_score(actual_labels,pred_labels)
ans

0.9432624113475178

## 로지스틱 회귀 모델

| 모델 | predict | predict_proba |
|-----|--------|---------------|
| statsmodels의 로지스틱 회귀 모델 | 확률값 (0~1 사이) | (없음) |
| scikit-learn의 로지스틱 회귀 모델 | 분류 결과 (0 또는 1) | 확률값 (0~1 사이) |

## 문제 2

제공된 데이터(`promotion_data.csv`)는 기업의 마케팅 홍보 활동에 따른 매출 데이터로,  
방문 횟수, 웹페이지 방문 시간, 광고 클릭 수, 홍보 예산 등에 따른 매출액(sales)에 관한 자료이다.  
이 데이터를 이용하여 통계 분석을 수행하고, 제시된 소문항에 답하시오.

---

### 제공 데이터 (`promotion_data.csv`)

### 종속 변수 (타겟 변수)
- sales : 매출액

### 독립 변수 (설명 변수)
- visit_count : 방문 횟수  
- page_time : 웹페이지 방문 시간(초)  
- ad_clicks : 광고 클릭 수  
- promotion_budget : 홍보 예산  
---

## 문제 2-1

홍보 전후 매출 평균이 35,000원과 같은지 단일 t검정(t-test)을 수행하고 p-value를 구하시오.

- 반올림하여 소수 셋째 자리까지 작성

---

## 문제 2-2

매출액(sales)과 다른 모든 변수들 간의 피어슨 상관계수(Pearson Correlation Coefficient)를 구하고, 그 중 상관관계가 가장 강한(절댓값이 가장 큰) 상관계수 값을 구하시오.

- 반올림하여 소수 셋째 자리까지 작성

---

## 문제 2-3

매출액(sales)을 종속변수, 나머지 모든 변수를 독립변수로 하여 회귀분석을 수행하시오.

절편을 포함한 모든 변수 중에서 p-value가 가장 작은 변수(통계적으로 가장 유의한 변수)의 회귀계수를 구하시오.

- 반올림하여 소수 셋째 자리까지 작성

In [40]:
# 2-1
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bae-v3/main/part4/ch11/promotion_data.csv")
df.head()

          sales  visit_count  page_time  ad_clicks  promotion_budget
0  35341.611727           36        168         18             11340
1  64757.849132           32        214         21             11224
2  40615.684241           56        172          6              5468
3  52009.480757           70        234          5              7486
4  32462.259065           27         88          8              7547

In [42]:
import pandas as pd
from scipy.stats import ttest_1samp
# 2. 단일 t-검정 수행 (sales 컬럼의 평균이 35,000과 같은지)
result = ttest_1samp(df['sales'], 35000)

# 3. p-value 추출 및 반올림 (소수 셋째 자리까지)
p_value = result.pvalue
ans = round(p_value, 3)

# 최종 정답 출력
print(ans)

0.168

In [46]:
# 2-2
"""
---

## 문제 2-2

매출액(sales)과 다른 모든 변수들 간의 피어슨 상관계수(Pearson Correlation Coefficient)를 구하고, 그 중 상관관계가 가장 강한(절댓값이 가장 큰) 상관계수 값을 구하시오.

- 반올림하여 소수 셋째 자리까지 작성

---
"""
a = df.corr(method="pearson")
a
# 0.575396

,sales,visit_count,page_time,ad_clicks,promotion_budget
sales,1.000000,0.044154,0.575396,-0.131915,-0.091270
visit_count,0.044154,1.000000,0.011349,0.078189,-0.089217
page_time,0.575396,0.011349,1.000000,-0.093688,-0.039554
ad_clicks,-0.131915,0.078189,-0.093688,1.000000,0.036940
promotion_budget,-0.091270,-0.089217,-0.039554,0.036940,1.000000

In [48]:
# 2-3
'''
## 문제 2-3

매출액(sales)을 종속변수, 나머지 모든 변수를 독립변수로 하여 회귀분석을 수행하시오.

절편을 포함한 모든 변수 중에서 p-value가 가장 작은 변수(통계적으로 가장 유의한 변수)의 회귀계수를 구하시오.

- 반올림하여 소수 셋째 자리까지 작성
'''
from statsmodels.formula.api import ols
model = ols("sales ~ visit_count + page_time + ad_clicks + promotion_budget",df).fit()
model.summary()
# 130.7392

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  sales   R-squared:                       0.343
Model:                            OLS   Adj. R-squared:                  0.330
Method:                 Least Squares   F-statistic:                     25.45
Date:                Fri, 12 Jun 2026   Prob (F-statistic):           5.60e-17
Time:                        18:51:56   Log-Likelihood:                -2160.2
No. Observations:                 200   AIC:                             4330.
Df Residuals:                     195   BIC:                             4347.
Df Model:                           4
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept         2.234e+04   4136.622      5.400      0.000    1.42e+04    3.05e+04
visit_count         28.7893     43.854      0.656      0.512     -57.701     115.279
page_time          130.7392     13.501      9.684      0.000     104.113     157.365
ad_clicks         -116.0846     85.288     -1.361      0.175    -284.290      52.121
promotion_budget    -0.3601      0.336     -1.072      0.285      -1.023       0.303
==============================================================================
Omnibus:                        0.318   Durbin-Watson:                   1.941
Prob(Omnibus):                  0.853   Jarque-Bera (JB):                0.286
Skew:                          -0.091   Prob(JB):                        0.867
Kurtosis:                       2.970   Cond. No.                     3.63e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.63e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""