# 작업형2

## 문제

제공된 학습용 데이터(`train.csv`)는 온라인 게임 플레이어의 활동 데이터이다. 학습용 데이터를 활용하여 유저 등급(`User_Level`)을 예측하는 모형을 개발하고, 모형을 평가용 데이터(`test.csv`)에 적용하여 유저 등급을 예측하시오. 예측 결과는 아래의 **[유의 사항]**과 **[제출 형식]**을 준수하여, CSV 파일(`result.csv`)을 생성하는 코드를 제출하시오.

## 유의 사항

1. 예측 결과는 **F1 Score(macro)** 평가 지표에 따라 평가함  
2. 타깃 변수(`User_Level`)는 **0, 1, 2 총 3개의 클래스로 구성됨**
   - `0`: Low
   - `1`: Medium
   - `2`: High

## 제출 형식

1. CSV 파일명: `result.csv`  
2. 예측 유저 등급 컬럼명: `pred`  
3. 제출 컬럼 개수: `pred` 컬럼 1개  
4. 평가용 데이터 개수와 예측 결과 데이터 개수 일치: **903개**

---

## 제공 데이터

- `train.csv`: 학습용 데이터, 약 **2,614개**
- `test.csv`: 평가용 데이터, 약 **903개**

## CSV 파일 형식 및 확인 방법

- CSV 파일명: `result.csv`
- 예측 유저 등급 컬럼명: `pred`
- 제출 CSV 파일 예시

```csv
pred
0
1
1
0
2
1
...

In [1]:
import pandas as pd
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/main/p4/11/game_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/main/p4/11/game_test.csv")

c:\Users\dnwpg\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
train.shape,test.shape

((2614, 10), (903, 9))

In [3]:
train.head()

,Guild_Contribution,Character_Level,Weekly_Playtime,Chat_Activity,Days_Inactive,Guild_Rank,PVP_Score,Quest_Completed,Item_Level,User_Level
0,184.76,20,46.11,97,14,0,397.70,93,230.45,0
1,987.68,120,58.79,0,0,5,999.00,471,250.54,2
2,274.90,40,41.66,136,0,8,633.58,245,253.44,1
3,581.71,83,15.56,186,1,3,144.42,0,200.18,1
4,129.14,19,28.74,135,4,3,240.33,209,176.01,0

In [4]:
train.value_counts()

Guild_Contribution  Character_Level  Weekly_Playtime  Chat_Activity  Days_Inactive  Guild_Rank  PVP_Score  Quest_Completed  Item_Level  User_Level
0.00                44               44.79            216            9              6           426.36     555              205.36      1             1
469.14              61               9.19             0              30             2           387.15     592              299.67      0             1
464.72              20               43.22            115            24             5           189.50     326              155.50      0             1
464.93              1                39.73            49             7              0           111.30     407              157.58      0             1
464.95              37               35.60            0              13             4           166.99     162              222.50      1             1
                                                                                                                                                     ..
262.43              3                56.56            98             5              0           254.54     172              346.09      0             1
262.72              56               49.84            89             23             0           540.34     262              373.89      1             1
262.76              120              41.74            104            10             5           338.76     308              283.76      1             1
262.86              44               45.16            92             12             2           211.13     463              327.52      1             1
987.68              120              70.00            117            5              6           575.89     800              387.98      2             1
Name: count, Length: 2614, dtype: int64

In [5]:
train.isnull().sum()

Guild_Contribution    0
Character_Level       0
Weekly_Playtime       0
Chat_Activity         0
Days_Inactive         0
Guild_Rank            0
PVP_Score             0
Quest_Completed       0
Item_Level            0
User_Level            0
dtype: int64

In [6]:
target = train["User_Level"]
train = train.drop("User_Level",axis=1)

In [21]:
from sklearn.model_selection import train_test_split
x_tr,x_val, y_tr,y_val = train_test_split(
    train,
    target,
    test_size = 0.2,
    random_state = 0,
    stratify = target
)
x_tr.shape

(2091, 9)

In [22]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=0,n_estimators = 37,max_depth = 100)
rf.fit(x_tr,y_tr)
pred = rf.predict(x_val)

In [23]:
from sklearn.metrics import f1_score
a = f1_score(y_val,pred,average="macro")
a

0.7507025914010946

In [24]:
ans = rf.predict(test)
result = pd.DataFrame({
    "pred" : ans
})
result

     pred
0       0
1       0
2       0
3       0
4       1
..    ...
898     0
899     0
900     0
901     0
902     1

[903 rows x 1 columns]

In [64]:
result.to_csv("result.csv",index=False)

### 풀이

11회 부터 완벽한 40점 코드는 없다.
- (필수) 랜덤포레스트 vs LightGBM 반드시 비교
- (선택) 불균형 처리 파라미터 정리 (분류)
| 함수 | 파라미터 | 설명 |
|---|---|---|
| `train_test_split` | `stratify=target` | 클래스 비율 유지 |
| `RandomForestClassifier` | `class_weight='balanced'` | 소수 클래스 가중치 증가 |
| `LGBMClassifier` | `class_weight='balanced'` | 소수 클래스 가중치 증가 |

- (선택) 전체 데이터 학습

In [ ]:
# 문제정의
# 평가: f1-macro
# target: User_Level
# 최종파일: result.csv(컬럼 1개 pred)

# 라이브러리 및 데이터 불러오기
import pandas as pd
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/main/p4/11/game_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/main/p4/11/game_test.csv")

# 탐색적 데이터 분석(EDA)
print("===== 데이터 크기 =====")
print("Train Shape:", train.shape)
print("Test Shape:", test.shape)

print("\n ===== 데이터 샘플 =====")
print(train.head())

print("\n ===== 데이터 정보(자료형) =====")
print(train.info())

print("\n ===== train 결측치 수 =====")
print(train.isnull().sum().sum())

print("\n ===== test 결측치 수 =====")
print(test.isnull().sum().sum())

print("\n ===== target unique 수 =====")
print(train['User_Level'].value_counts())

===== 데이터 크기 =====
Train Shape: (2614, 10)
Test Shape: (903, 9)

 ===== 데이터 샘플 =====
   Guild_Contribution  Character_Level  Weekly_Playtime  Chat_Activity  \
0              184.76               20            46.11             97
1              987.68              120            58.79              0
2              274.90               40            41.66            136
3              581.71               83            15.56            186
4              129.14               19            28.74            135

   Days_Inactive  Guild_Rank  PVP_Score  Quest_Completed  Item_Level  \
0             14           0     397.70               93      230.45
1              0           5     999.00              471      250.54
2              0           8     633.58              245      253.44
3              1           3     144.42                0      200.18
4              4           3     240.33              209      176.01

   User_Level
0           0
1           2
2           1
3           1
4           0

 ===== 데이터 정보(자료형) =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2614 entries, 0 to 2613
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Guild_Contribution  2614 non-null   float64
 1   Character_Level     2614 non-null   int64
 2   Weekly_Playtime     2614 non-null   float64
 3   Chat_Activity       2614 non-null   int64
 4   Days_Inactive       2614 non-null   int64
 5   Guild_Rank          2614 non-null   int64
 6   PVP_Score           2614 non-null   float64
 7   Quest_Completed     2614 non-null   int64
 8   Item_Level          2614 non-null   float64
 9   User_Level          2614 non-null   int64
dtypes: float64(4), int64(6)
memory usage: 204.3 KB
None

 ===== train 결측치 수 =====
0

 ===== test 결측치 수 =====
0

 ===== target unique 수 =====
User_Level
1    1313
0    1165
2     136
Name: count, dtype: int64

In [ ]:
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/main/p4/11/game_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/main/p4/11/game_test.csv")

# 데이터 전처리
target = train.pop('User_Level')

# 검증데이터 분리
from sklearn.model_selection import train_test_split
X_tr, X_val, y_tr, y_val = train_test_split(train, target, test_size=0.2, random_state=0)

# 랜덤포레스트
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=0)
rf.fit(X_tr, y_tr)
pred = rf.predict(X_val)

# macro F1 score
from sklearn.metrics import f1_score
print("랜덤포레스트")
print(f1_score(y_val, pred, average='macro'))

# LightGBM
import lightgbm as lgb
lg = lgb.LGBMClassifier(random_state=0, verbose=-1)
lg.fit(X_tr, y_tr)
pred = lg.predict(X_val)
print("lightgbm")
print(f1_score(y_val, pred, average='macro'))

# 최종 제출 파일 (lightGBM)
pred = lg.predict(test)
result = pd.DataFrame({
    'pred':pred
})
result.to_csv("result.csv", index=False)

랜덤포레스트
0.7241845968568211
lightgbm
0.7989718332478102

## 심화

In [ ]:
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/main/p4/11/game_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/inf/main/p4/11/game_test.csv")

# 데이터 전처리
target = train.pop('User_Level')

# 검증데이터 분리
from sklearn.model_selection import train_test_split
X_tr, X_val, y_tr, y_val = train_test_split(train, target, test_size=0.2, random_state=0, stratify=target)

# 랜덤포레스트
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=0, class_weight='balanced')
rf.fit(X_tr, y_tr)
pred = rf.predict(X_val)

# macro F1 score
from sklearn.metrics import f1_score
print("랜덤포레스트")
print(f1_score(y_val, pred, average='macro'))

# LightGBM
import lightgbm as lgb
lg = lgb.LGBMClassifier(random_state=0, verbose=-1, class_weight='balanced')

lg.fit(X_tr, y_tr)
pred = lg.predict(X_val)
print("lightgbm")
print(f1_score(y_val, pred, average='macro'))

# 최종 제출 파일 (lightGBM)
pred = lg.predict(test)
result = pd.DataFrame({
    'pred':pred
})
result.to_csv("result.csv", index=False)

랜덤포레스트
0.6978899292299431
lightgbm
0.7551294728633561

In [ ]:
# LightGBM - 전체 데이터로 학습
lg = lgb.LGBMClassifier(random_state=0, verbose=-1, class_weight='balanced')
lg.fit(train, target)

# 최종 제출 파일 (lightGBM)
pred = lg.predict(test)
result = pd.DataFrame({
    'pred': pred
})
result.to_csv("result.csv", index=False)

In [ ]:
# 1. pred 행의 수와 test의 행의 수 비교
print("pred: ",pred.shape)# test 행의 수: 903

# 2. 생성한 csv 확인
print(pd.read_csv("result.csv").head())

pred:  (903,)
   pred
0     0
1     0
2     0
3     0
4     1